//! User copper lists (`Copper Off` mode, +W.s:6790-6907) and the display
//! they produce.
//!
//! While the copper is off, the program writes its own copper list with
//! `Cop Wait` / `Cop Move` (or `Loke` at `Cop Logic`) and the frame is made
//! by running that list line by line, the way the Amiga copper and display
//! chips would:
//!
//! * `WAIT` / `SKIP` compare the beam position (vertical position modulo
//!   256 and the horizontal position, with their masks). A `MOVE` that
//!   follows a wait for a horizontal position up to [`LATE_H`] changes the
//!   whole line it waits for; after a wait further right the copper goes
//!   on at the next line, as the real one does after the classic
//!   `$FFDF,$FFFE` (colour changes in the middle of a line are not
//!   reproduced).
//! * Registers used for the picture: `DMACON` (bitplane DMA), `BPLCON0`
//!   (planes, hires, HAM, dual playfield), `BPLCON1` (fine scrolling),
//!   `BPLCON2` (playfield priority), `DIWSTRT`/`DIWSTOP`, `DDFSTRT`/`DDFSTOP`,
//!   `BPL1MOD`/`BPL2MOD`, `BPLxPT` and the 32 colour registers. Extra half
//!   brite, HAM6 and dual playfield are decoded. Interlace, sprites and
//!   the other registers are ignored.
//! * Bitplane pointers are chip memory addresses. The values given by
//!   `Logbase(n)` / `Phybase(n)` and the ones put in the lists generated by
//!   `=Cop Logic` point into screen bitmaps (see [`Chip::decode`]); other
//!   addresses read the emulated memory.

use crate::display::{DISPLAY_HEIGHT, DISPLAY_WIDTH, HW_X0, HW_Y0, rgb12_to_rgba};

/// Length of each copper list (`T_CopLong`, +Interpreter_Config.s:32).
pub const LIST_LENGTH: u32 = 12 * 1024;
/// Chip memory addresses of the two copper lists (logic / physic).
pub const LIST_A: u32 = 0x0004_0000;
pub const LIST_B: u32 = 0x0004_4000;
/// Number of lines of a PAL frame.
pub const FRAME_LINES: i32 = 313;
/// Lines of the display shown by the renderer.
pub const SHOWN_LINES: usize = (DISPLAY_HEIGHT / 2) as usize;
/// Last horizontal position (colour clocks) of a wait whose moves still
/// change the line it waits for.
pub const LATE_H: u16 = 0xD0;
/// Highest horizontal beam position.
const MAX_H: u16 = 0xE2;

/// Register offsets ($DFF000 + offset).
pub mod reg {
    pub const DIWSTRT: u16 = 0x8E;
    pub const DIWSTOP: u16 = 0x90;
    pub const DDFSTRT: u16 = 0x92;
    pub const DDFSTOP: u16 = 0x94;
    pub const DMACON: u16 = 0x96;
    pub const BPL1PT: u16 = 0xE0;
    pub const BPLCON0: u16 = 0x100;
    pub const BPLCON1: u16 = 0x102;
    pub const BPLCON2: u16 = 0x104;
    pub const BPL1MOD: u16 = 0x108;
    pub const BPL2MOD: u16 = 0x10A;
    pub const COLOR00: u16 = 0x180;
}

/// DMACON bits: master enable and bitplane DMA.
const DMAEN: u16 = 0x0200;
const BPLEN: u16 = 0x0100;

/// Where a bitplane pointer points: a plane of a screen bitmap (the chunky
/// bitmap byte bit `plane`), or plain memory.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum PlaneSrc {
    Bitmap {
        screen: usize,
        bitmap: usize,
        plane: u8,
    },
    Memory,
}

/// A bitplane pointer: the source decoded when it was loaded and the byte
/// offset from there (advanced by the display DMA without decoding again).
#[derive(Clone, Copy, Debug)]
pub struct PlanePtr {
    pub raw: u32,
    pub src: PlaneSrc,
    pub offset: i64,
}

impl Default for PlanePtr {
    fn default() -> Self {
        PlanePtr {
            raw: 0,
            src: PlaneSrc::Memory,
            offset: 0,
        }
    }
}

/// Access to chip memory for the copper and the display.
pub trait Chip {
    /// Word at `addr` (copper list).
    fn word(&self, addr: u32) -> u16;
    /// Decodes a bitplane pointer value: returns the source and the byte
    /// offset in it.
    fn decode(&self, addr: u32) -> (PlaneSrc, i64);
    /// Fills `out` with the bitplane bytes at `offset` in `src`.
    fn plane_bytes(&self, src: PlaneSrc, offset: i64, out: &mut [u8]);
}

/// State of the user copper (`T_CopON`, `T_CopLogic`, `T_CopPos`...) and
/// of the custom chip registers it writes.
#[derive(Clone, Debug)]
pub struct Copper {
    /// The copper list is built by AMOS (`Copper On`).
    pub on: bool,
    pub logic: u32,
    pub physic: u32,
    /// Next instruction address (`T_CopPos`).
    pub pos: u32,
    /// The wait for line 255 has been inserted (`T_Cop255`).
    pub cop255: bool,
    /// Custom registers $DFF000-$DFF1FE (word index), kept between frames.
    pub regs: Vec<u16>,
    pub planes: [PlanePtr; 6],
}

impl Default for Copper {
    fn default() -> Self {
        let mut regs = vec![0u16; 256];
        regs[(reg::DMACON / 2) as usize] = DMAEN | 0x00F0;
        Copper {
            on: true,
            logic: LIST_A,
            physic: LIST_B,
            pos: LIST_A,
            cop255: false,
            regs,
            planes: Default::default(),
        }
    }
}

/// `Cop Wait` / `Cop Move` errors (+W.s:6879): "Copper not disabled",
/// "Copper list too long", "Illegal copper parameter".
pub const ERR_NOT_DISABLED: u16 = 76;
pub const ERR_TOO_LONG: u16 = 77;
pub const ERR_PARAM: u16 = 78;

/// Encodes `Cop Wait x,y,maskx,masky` (`TCopWt`): the two words.
pub fn wait_words(x: i32, y: i32, mx: i32, my: i32) -> (u16, u16) {
    let w1 = ((y as u16) << 8) | (((x as u16) >> 1) & 0xFE) | 1;
    let w2 = ((my as u16) << 8) | (((mx as u16) >> 1) & 0xFE);
    (w1, w2)
}

/// Snapshot of the registers that make a line.
struct LineRegs {
    dmacon: u16,
    bplcon0: u16,
    bplcon1: u16,
    bplcon2: u16,
    diwstrt: u16,
    diwstop: u16,
    ddfstrt: u16,
    ddfstop: u16,
    mods: (i16, i16),
    colours: [u16; 32],
}

impl Copper {
    fn r(&self, r: u16) -> u16 {
        self.regs[(r / 2) as usize & 255]
    }

    /// A MOVE to a custom register.
    fn write(&mut self, chip: &dyn Chip, r: u16, v: u16) {
        let r = r & 0x1FE;
        if r == reg::DMACON {
            let d = &mut self.regs[(reg::DMACON / 2) as usize];
            if v & 0x8000 != 0 {
                *d |= v & 0x7FFF;
            } else {
                *d &= !v;
            }
            return;
        }
        self.regs[(r / 2) as usize] = v;
        if (reg::BPL1PT..reg::BPL1PT + 24).contains(&r) {
            let p = ((r - reg::BPL1PT) / 4) as usize;
            let ptr = &mut self.planes[p];
            ptr.raw = if r & 2 == 0 {
                (ptr.raw & 0xFFFF) | ((v as u32) << 16)
            } else {
                (ptr.raw & 0xFFFF_0000) | v as u32
            };
            let (src, offset) = chip.decode(ptr.raw);
            ptr.src = src;
            ptr.offset = offset;
        }
    }

    fn line_regs(&self) -> LineRegs {
        let mut colours = [0u16; 32];
        for (i, c) in colours.iter_mut().enumerate() {
            *c = self.r(reg::COLOR00 + 2 * i as u16) & 0xFFF;
        }
        LineRegs {
            dmacon: self.r(reg::DMACON),
            bplcon0: self.r(reg::BPLCON0),
            bplcon1: self.r(reg::BPLCON1),
            bplcon2: self.r(reg::BPLCON2),
            diwstrt: self.r(reg::DIWSTRT),
            diwstop: self.r(reg::DIWSTOP),
            ddfstrt: self.r(reg::DDFSTRT),
            ddfstop: self.r(reg::DDFSTOP),
            mods: (self.r(reg::BPL1MOD) as i16, self.r(reg::BPL2MOD) as i16),
            colours,
        }
    }

    /// Runs the physic list for one frame and renders the display:
    /// `DISPLAY_WIDTH` x [`SHOWN_LINES`] RGBA pixels (one row per raster
    /// line from `HW_Y0`, one pixel per hires pixel).
    pub fn render(&mut self, chip: &dyn Chip, out: &mut Vec<u8>) {
        let w = DISPLAY_WIDTH as usize;
        out.clear();
        out.resize(w * SHOWN_LINES * 4, 0);
        let mut pc = self.physic;
        let mut halted = false;
        let mut row = Vec::new();
        for line in 0..FRAME_LINES {
            let vp = (line & 0xFF) as u16;
            let mut steps = 0;
            while !halted {
                steps += 1;
                if steps > 4096 {
                    halted = true;
                    break;
                }
                let w1 = chip.word(pc);
                let w2 = chip.word(pc.wrapping_add(2));
                if w1 & 1 == 0 {
                    pc = pc.wrapping_add(4);
                    self.write(chip, w1, w2);
                    continue;
                }
                // WAIT / SKIP: vertical bit 7 is always compared.
                let (v, h) = (w1 >> 8, w1 & 0xFE);
                let (vm, hm) = ((w2 >> 8) | 0x80, w2 & 0xFE);
                let (bv, ev) = (vp & vm, v & vm);
                let ok = bv > ev || (bv == ev && (MAX_H & hm) >= (h & hm));
                if w2 & 1 != 0 {
                    // SKIP the next instruction if the beam is past.
                    pc = pc.wrapping_add(if ok { 8 } else { 4 });
                    continue;
                }
                if !ok {
                    if w1 == 0xFFFF && w2 == 0xFFFE {
                        halted = true;
                    }
                    break;
                }
                pc = pc.wrapping_add(4);
                if h > LATE_H && bv == ev {
                    break;
                }
            }
            let lr = self.line_regs();
            self.display_line(chip, line, &lr, &mut row);
            if (HW_Y0..HW_Y0 + SHOWN_LINES as i32).contains(&line) {
                let o = (line - HW_Y0) as usize * w * 4;
                out[o..o + w * 4].copy_from_slice(&row);
            }
        }
    }

    /// Makes one raster line (`row` = DISPLAY_WIDTH RGBA pixels) and moves
    /// the bitplane pointers on.
    fn display_line(&mut self, chip: &dyn Chip, line: i32, lr: &LineRegs, row: &mut Vec<u8>) {
        let w = DISPLAY_WIDTH as usize;
        row.clear();
        let back = rgb12_to_rgba(lr.colours[0]);
        for _ in 0..w {
            row.extend_from_slice(&back);
        }
        let hires = lr.bplcon0 & 0x8000 != 0;
        let mut nplanes = ((lr.bplcon0 >> 12) & 7) as usize;
        if nplanes > 6 {
            nplanes = 4;
        }
        let ham = lr.bplcon0 & 0x0800 != 0 && nplanes == 6;
        let dpf = lr.bplcon0 & 0x0400 != 0;
        let vstart = (lr.diwstrt >> 8) as i32;
        let vstop = ((lr.diwstop >> 8) | if lr.diwstop & 0x8000 == 0 { 0x100 } else { 0 }) as i32;
        let fetch = lr.dmacon & (DMAEN | BPLEN) == (DMAEN | BPLEN)
            && nplanes > 0
            && line >= vstart
            && line < vstop;
        if !fetch {
            return;
        }
        // Bytes fetched per line and position of the first pixel.
        let (ddf0, ddf1) = ((lr.ddfstrt & 0xFC) as i32, (lr.ddfstop & 0xFC) as i32);
        let bytes = if hires {
            ((ddf1 - ddf0) / 4 + 2) * 2
        } else {
            ((ddf1 - ddf0) / 8 + 1) * 2
        }
        .max(0) as usize;
        let x0 = ddf0 * 2 + if hires { 8 } else { 16 };
        let mut data = vec![vec![0u8; bytes]; nplanes];
        for (p, d) in data.iter_mut().enumerate() {
            let ptr = &mut self.planes[p];
            chip.plane_bytes(ptr.src, ptr.offset, d);
            let m = if p & 1 == 0 { lr.mods.0 } else { lr.mods.1 };
            ptr.offset += bytes as i64 + m as i64;
            ptr.raw = ptr.raw.wrapping_add((bytes as i64 + m as i64) as u32);
        }
        let hstart = (lr.diwstrt & 0xFF) as i32 - 1;
        let hstop = ((lr.diwstop & 0xFF) | 0x100) as i32 - 1;
        let delay = [(lr.bplcon1 & 15) as i32, ((lr.bplcon1 >> 4) & 15) as i32];
        let mut ham_colour = lr.colours[0];
        for i in 0..w {
            let hx = HW_X0 + (i / 2) as i32;
            if hx < hstart || hx >= hstop {
                continue;
            }
            // Pixel number in the fetched data (hires pixels in hires).
            let col = if hires {
                2 * (HW_X0 - x0) + i as i32
            } else {
                hx - x0
            };
            let mut idx = 0u8;
            for (p, d) in data.iter().enumerate() {
                let c = col - delay[p & 1] * if hires { 2 } else { 1 };
                if c >= 0
                    && ((c >> 3) as usize) < d.len()
                    && d[(c >> 3) as usize] & (0x80 >> (c & 7)) != 0
                {
                    idx |= 1 << p;
                }
            }
            let rgb = if ham {
                let v = (idx & 15) as u16;
                ham_colour = match idx >> 4 {
                    0 => lr.colours[v as usize],
                    1 => (ham_colour & 0xFF0) | v,
                    2 => (ham_colour & 0x0FF) | (v << 8),
                    _ => (ham_colour & 0xF0F) | (v << 4),
                };
                ham_colour
            } else if dpf {
                let pf1 = (idx & 1) | ((idx >> 1) & 2) | ((idx >> 2) & 4);
                let pf2 = ((idx >> 1) & 1) | ((idx >> 2) & 2) | ((idx >> 3) & 4);
                let pf2_front = lr.bplcon2 & 0x40 != 0;
                let c = match (pf1, pf2) {
                    (0, 0) => 0,
                    (a, 0) => a,
                    (0, b) => b + 8,
                    (a, b) => {
                        if pf2_front {
                            b + 8
                        } else {
                            a
                        }
                    }
                };
                lr.colours[c as usize]
            } else if idx >= 32 {
                (lr.colours[(idx & 31) as usize] >> 1) & 0x777
            } else {
                lr.colours[idx as usize]
            };
            row[i * 4..i * 4 + 4].copy_from_slice(&rgb12_to_rgba(rgb));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashMap;

    /// A flat memory with one 32x4 chunky "screen" at $200000.
    struct Mem {
        words: HashMap<u32, u16>,
        bitmap: Vec<u8>,
    }

    impl Chip for Mem {
        fn word(&self, addr: u32) -> u16 {
            self.words.get(&addr).copied().unwrap_or(0)
        }
        fn decode(&self, addr: u32) -> (PlaneSrc, i64) {
            if addr >= 0x200000 {
                let o = addr - 0x200000;
                (
                    PlaneSrc::Bitmap {
                        screen: 0,
                        bitmap: 0,
                        plane: (o / 0x2000) as u8,
                    },
                    (o % 0x2000) as i64,
                )
            } else {
                (PlaneSrc::Memory, addr as i64)
            }
        }
        fn plane_bytes(&self, src: PlaneSrc, offset: i64, out: &mut [u8]) {
            let PlaneSrc::Bitmap { plane, .. } = src else {
                return out.fill(0);
            };
            for (k, b) in out.iter_mut().enumerate() {
                let o = offset as usize + k;
                let (y, xb) = (o / 4, o % 4);
                *b = 0;
                for bit in 0..8 {
                    let px = self.bitmap.get(y * 32 + xb * 8 + bit).copied().unwrap_or(0);
                    if px >> plane & 1 != 0 {
                        *b |= 0x80 >> bit;
                    }
                }
            }
        }
    }

    fn list(m: &mut Mem, start: u32, l: &[(u16, u16)]) {
        for (i, &(a, b)) in l.iter().enumerate() {
            m.words.insert(start + 4 * i as u32, a);
            m.words.insert(start + 4 * i as u32 + 2, b);
        }
    }

    fn pixel(out: &[u8], hx: i32, line: i32) -> [u8; 3] {
        let o =
            ((line - HW_Y0) as usize * DISPLAY_WIDTH as usize + ((hx - HW_X0) * 2) as usize) * 4;
        [out[o], out[o + 1], out[o + 2]]
    }

    #[test]
    fn colour_bars_and_bitplanes() {
        let mut m = Mem {
            words: HashMap::new(),
            bitmap: vec![0; 32 * 4],
        };
        m.bitmap[0] = 1;
        m.bitmap[32 + 1] = 2;
        let mut c = Copper::default();
        let (w1, w2) = wait_words(0, 100, -1, -1);
        let (e1, e2) = wait_words(0, 110, -1, -1);
        list(
            &mut m,
            c.physic,
            &[
                (reg::COLOR00, 0x00F),
                (reg::COLOR00 + 2, 0xF00),
                (reg::COLOR00 + 4, 0x0F0),
                (reg::DIWSTRT, 0x5081),
                (reg::DIWSTOP, 0x60C1),
                (reg::DDFSTRT, 0x38),
                (reg::DDFSTOP, 0xD0),
                (reg::BPL1MOD, (4i16 - 40) as u16),
                (reg::BPL2MOD, (4i16 - 40) as u16),
                (reg::BPL1PT, 0x20),
                (reg::BPL1PT + 2, 0),
                (reg::BPL1PT + 4, 0x20),
                (reg::BPL1PT + 6, 0x2000),
                (reg::BPLCON0, 0x2200),
                (reg::DMACON, 0x8100),
                (w1, w2),
                (reg::COLOR00, 0xFFF),
                (e1, e2),
                (reg::COLOR00, 0x000),
                (0xFFFF, 0xFFFE),
            ],
        );
        let mut out = Vec::new();
        c.render(&m, &mut out);
        assert_eq!(pixel(&out, 100, 60), [0, 0, 0xFF]);
        assert_eq!(pixel(&out, 100, 105), [0xFF, 0xFF, 0xFF]);
        assert_eq!(pixel(&out, 100, 120), [0, 0, 0]);
        // Bitplanes from line $50 at x 128: pixel 0 colour 1, (1,1) colour 2.
        assert_eq!(pixel(&out, 128, 0x50), [0xFF, 0, 0]);
        assert_eq!(pixel(&out, 129, 0x50), [0, 0, 0xFF]);
        assert_eq!(pixel(&out, 129, 0x51), [0, 0xFF, 0]);
        // DMA stays on: the registers are kept for the next frame.
        c.render(&m, &mut out);
        assert_eq!(pixel(&out, 128, 0x50), [0xFF, 0, 0]);
    }

    #[test]
    fn end_of_list_and_wrap_wait() {
        let mut m = Mem {
            words: HashMap::new(),
            bitmap: vec![],
        };
        let mut c = Copper::default();
        let (w1, w2) = wait_words(0, 4, -1, -1);
        list(
            &mut m,
            c.physic,
            &[
                (0xFFE1, 0xFFFE),
                (w1, w2),
                (reg::COLOR00, 0xF00),
                (0xFFFF, 0xFFFE),
                (reg::COLOR00, 0x0F0),
            ],
        );
        let mut out = Vec::new();
        c.render(&m, &mut out);
        assert_eq!(pixel(&out, 200, 200), [0, 0, 0]);
        assert_eq!(pixel(&out, 200, 260), [0xFF, 0, 0]);
        assert_eq!(pixel(&out, 200, 300), [0xFF, 0, 0]);
    }
}
