#!/usr/bin/env python3
"""Generate crates/amos-core/src/tokens/table.rs from the AMOS Pro 68000 sources.

The token value of a keyword is the byte offset of its entry in the library
token table, so the tables are rebuilt by assembling the dc.w/dc.b token
table sources exactly as Devpac would (see amos_tokens.py).

Usage: python3 tools/gen_tokens_rs.py
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import amos_tokens as at  # noqa: E402

ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, "AMOS-Professional-365")
OUT = os.path.join(ROOT, "crates", "amos-core", "src", "tokens", "table.rs")


def routine_names(path, srcline):
    """Map entry offset -> (instruction routine, function routine) symbols."""
    with open(path, "rb") as f:
        lines = f.read().decode("latin-1").splitlines()
    names = {}
    for off, no in srcline.items():
        line = lines[no - 1]
        m = re.search(r"(?i)dc\.w\s+([^\s,]+)\s*,\s*([^\s;]+)", line)
        if m:
            k = re.search(r"//\$([0-9A-Fa-f]{2})\$([0-9A-Fa-f]{2})\$([0-9A-Fa-f]{2})\$([0-9A-Fa-f]{2})", line)
            kwik = [int(x, 16) for x in k.groups()] if k else [0, 0, 0, 0]
            names[off] = (m.group(1), m.group(2), kwik)
    return names


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit(out, ident, entries, names):
    out.append("pub static %s: &[TokenDef] = &[" % ident)
    for off in sorted(entries):
        e = entries[off]
        inst, func, kwik = names.get(off, ("", "", [0, 0, 0, 0]))
        out.append(
            "    TokenDef { token: 0x%04X, name: %s, params: %s, term: %d, inst: %s, func: %s, verif: [0x%02X, 0x%02X, 0x%02X, 0x%02X] },"
            % (off, rust_str(e.name), rust_str(e.params), e.term, rust_str(inst), rust_str(func), *kwik)
        )
    out.append("];")
    out.append("")


EXT_PREFIX = {1: "MUSIC", 2: "COMPACT", 3: "REQUEST", 4: "TD", 5: "COMP", 6: "IO"}
OP_NAMES = {" xor ": "XOR", " or ": "OR", " and ": "AND", "<>": "NE", "><": "NE2", "<=": "LE",
            "=<": "LE2", ">=": "GE", "=>": "GE2", "=": "EQ", "<": "LT", ">": "GT", "+": "PLUS",
            "-": "MINUS", " mod ": "MOD", "*": "MUL", "/": "DIV", "^": "POW"}
PUNCT = {":": "COLON", ",": "COMMA", ";": "SEMICOLON", "#": "HASH", "(": "PAR1", ")": "PAR2",
         "[": "BRA1", "]": "BRA2"}


def const_name(name):
    n = name.strip()
    if n in PUNCT:
        return PUNCT[n]
    n = n.replace(" #", " hash").replace("$", "_s").replace("#", "_f")
    n = re.sub(r"[^A-Za-z0-9_]+", "_", n)
    n = re.sub(r"_+", "_", n).strip("_").upper()
    if not n or n[0].isdigit():
        n = "T_" + n
    return n


def emit_consts(out, entries, prefix, kind):
    """Constants named after the keyword; overload variants get _2, _3..."""
    seen = {}
    for off in sorted(entries):
        e = entries[off]
        if not e.name or e.name.startswith("@"):
            continue
        base = const_name(e.name)
        if prefix:
            base = prefix + "_" + base
        seen[base] = seen.get(base, 0) + 1
        nm = base if seen[base] == 1 else "%s_%d" % (base, seen[base])
        out.append("/// `%s` %s" % (e.name.strip(), e.params))
        out.append("pub const %s: %s = 0x%04X;" % (nm, kind, off))


def main():
    out = [
        "// @generated by tools/gen_tokens_rs.py from the AMOS Professional sources. Do not edit.",
        "",
        "use super::TokenDef;",
        "",
    ]
    tb, sl = at.assemble_token_table(os.path.join(SRC, "+Lib.s"), r"^C_Tk\b")
    emit(out, "MAIN", at.walk_table(tb, sl), routine_names(os.path.join(SRC, "+Lib.s"), sl))
    ops = at.operator_table(os.path.join(SRC, "+Edit.s"))
    emit(out, "OPERATORS", ops, {})
    idents = []
    for n, (s, _) in sorted(at.EXTENSIONS.items()):
        lab = r"^TokenTable" if s == "+3d.s" else r"^C_Tk\b"
        path = os.path.join(SRC, s)
        tb, sl = at.assemble_token_table(path, lab)
        ident = "EXT_%d" % n
        emit(out, ident, at.walk_table(tb, sl), routine_names(path, sl))
        idents.append(ident)
    out.append("/// Extension tables indexed by extension slot (slot 0 is the main library).")
    out.append("pub static EXTENSIONS: [&[TokenDef]; %d] = [MAIN, %s];" % (len(idents) + 1, ", ".join(idents)))
    consts = ["// @generated by tools/gen_tokens_rs.py. Do not edit.", "",
              "//! Token values by keyword name. Overloaded variants are suffixed `_2`, `_3`...", "",
              "#![allow(dead_code)]", ""]
    main_entries = at.walk_table(*at.assemble_token_table(os.path.join(SRC, "+Lib.s"), r"^C_Tk\b"))
    emit_consts(consts, main_entries, "", "u16")
    for k, e in sorted(ops.items()):
        consts.append("pub const OP_%s: u16 = 0x%04X;" % (OP_NAMES[e.name], k))
    for n, (s_, _) in sorted(at.EXTENSIONS.items()):
        lab = r"^TokenTable" if s_ == "+3d.s" else r"^C_Tk\b"
        emit_consts(consts, at.walk_table(*at.assemble_token_table(os.path.join(SRC, s_), lab)), EXT_PREFIX[n], "u16")
    with open(os.path.join(os.path.dirname(OUT), "names.rs"), "w") as f:
        f.write("\n".join(consts) + "\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    print("wrote", OUT)


if __name__ == "__main__":
    main()
