#!/usr/bin/env python3
"""Generate crates/amos-core/src/errors/messages.rs from +Editor_Config.s.

The original interpreter has no error strings: they live in the editor
configuration (EdT macro lists). Each list starts with `dc.l .X2-.X1`.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "AMOS-Professional-365", "+Editor_Config.s")
OUT = os.path.join(ROOT, "crates", "amos-core", "src", "errors", "messages.rs")

LISTS = {".Sys2-.Sys1": "SYSTEM", "Ed2-Ed1": "EDITOR", ".Test2-.Test1": "TEST", ".Error2-.Error1": "RUNTIME"}


def main():
    lines = open(SRC, "rb").read().decode("latin-1").splitlines()
    lists, cur = {}, None
    for l in lines:
        m = re.match(r"\s*dc\.l\s+(\S+)", l)
        if m:
            cur = LISTS.get(m.group(1))
            if cur:
                lists[cur] = []
            continue
        if cur is None:
            continue
        if re.match(r"(?i)\s*dc\.b\s+0,\$ff", l):
            cur = None
            continue
        m = re.match(r"^\S*\s+EdT\s+(\d+),<(.*)>", l)
        if m:
            text = m.group(2)
            lists[cur].append((int(m.group(1)), text))
    out = ["// @generated by tools/gen_messages_rs.py from +Editor_Config.s. Do not edit.", ""]
    for name in ["SYSTEM", "EDITOR", "TEST", "RUNTIME"]:
        out.append("pub static %s: &[(u16, &str)] = &[" % name)
        for n, t in lists[name]:
            esc = t.replace("\\", "\\\\").replace('"', '\\"')
            out.append('    (%d, "%s"),' % (n, esc))
        out.append("];")
        out.append("")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    open(OUT, "w", encoding="utf-8").write("\n".join(out))
    print("wrote", OUT, {k: len(v) for k, v in lists.items()})


main()
