[package]
name = "amos-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
default-run = "amos-cli"

[dependencies]
amos-build = { version = "0.1.0", path = "../amos-build" }
amos-compiler = { version = "0.1.0", path = "../amos-compiler" }
amos-core = { version = "0.1.0", path = "../amos-core" }
amos-wasmhost = { version = "0.1.0", path = "../amos-wasmhost" }
png = "0.18.1"
