// @generated by tools/gen_tokens_rs.py. Do not edit.

//! Token values by keyword name. Overloaded variants are suffixed `_2`, `_3`...

#![allow(dead_code)]

/// `:` 
pub const COLON: u16 = 0x0054;
/// `,` O
pub const COMMA: u16 = 0x005C;
/// `;` O
pub const SEMICOLON: u16 = 0x0064;
/// `#` O
pub const HASH: u16 = 0x006C;
/// `(` O
pub const PAR1: u16 = 0x0074;
/// `)` O
pub const PAR2: u16 = 0x007C;
/// `[` O
pub const BRA1: u16 = 0x0084;
/// `]` O
pub const BRA2: u16 = 0x008C;
/// `to` 
pub const TO: u16 = 0x0094;
/// `not` 
pub const NOT: u16 = 0x009C;
/// `swap` 
pub const SWAP: u16 = 0x00A6;
/// `def fn` 
pub const DEF_FN: u16 = 0x00B0;
/// `fn` 
pub const FN: u16 = 0x00BC;
/// `follow off` I
pub const FOLLOW_OFF: u16 = 0x00C4;
/// `follow` I
pub const FOLLOW: u16 = 0x00D4;
/// `resume next` I
pub const RESUME_NEXT: u16 = 0x00E0;
/// `inkey$` 2
pub const INKEY_S: u16 = 0x00F2;
/// `repeat$` 22,0
pub const REPEAT_S: u16 = 0x00FE;
/// `zone$` 22,0
pub const ZONE_S: u16 = 0x010E;
/// `border$` 22,0
pub const BORDER_S: u16 = 0x011C;
/// `double buffer` I
pub const DOUBLE_BUFFER: u16 = 0x012C;
/// `start` 00
pub const START: u16 = 0x0140;
/// `length` 00
pub const LENGTH: u16 = 0x014C;
/// `doke` I0,0
pub const DOKE: u16 = 0x015A;
/// `on menu del` I
pub const ON_MENU_DEL: u16 = 0x0168;
/// `on menu on` I
pub const ON_MENU_ON: u16 = 0x017A;
/// `on menu off` I
pub const ON_MENU_OFF: u16 = 0x018A;
/// `every on` I
pub const EVERY_ON: u16 = 0x019C;
/// `every off` I
pub const EVERY_OFF: u16 = 0x01AA;
/// `logbase` 00
pub const LOGBASE: u16 = 0x01BA;
/// `logic` 0
pub const LOGIC: u16 = 0x01C8;
/// `logic` 00
pub const LOGIC_2: u16 = 0x01D4;
/// `asc` 02
pub const ASC: u16 = 0x01DC;
/// `as` I
pub const AS: u16 = 0x01E6;
/// `call` I
pub const CALL: u16 = 0x01EE;
/// `execall` 00
pub const EXECALL: u16 = 0x01F8;
/// `gfxcall` 00
pub const GFXCALL: u16 = 0x0206;
/// `doscall` 00
pub const DOSCALL: u16 = 0x0214;
/// `intcall` 00
pub const INTCALL: u16 = 0x0222;
/// `freeze` I
pub const FREEZE: u16 = 0x0230;
/// `for` 
pub const FOR: u16 = 0x023C;
/// `next` 
pub const NEXT: u16 = 0x0246;
/// `repeat` 
pub const REPEAT: u16 = 0x0250;
/// `until` 
pub const UNTIL: u16 = 0x025C;
/// `while` 
pub const WHILE: u16 = 0x0268;
/// `wend` 
pub const WEND: u16 = 0x0274;
/// `do` 
pub const DO: u16 = 0x027E;
/// `loop` 
pub const LOOP: u16 = 0x0286;
/// `exit if` 
pub const EXIT_IF: u16 = 0x0290;
/// `exit` 
pub const EXIT: u16 = 0x029E;
/// `goto` 
pub const GOTO: u16 = 0x02A8;
/// `gosub` 
pub const GOSUB: u16 = 0x02B2;
/// `if` 
pub const IF: u16 = 0x02BE;
/// `then` 
pub const THEN: u16 = 0x02C6;
/// `else` 
pub const ELSE: u16 = 0x02D0;
/// `end if` 
pub const END_IF: u16 = 0x02DA;
/// `on error` 
pub const ON_ERROR: u16 = 0x02E6;
/// `on break proc` 
pub const ON_BREAK_PROC: u16 = 0x02F4;
/// `on menu` I0
pub const ON_MENU: u16 = 0x0308;
/// `on` 
pub const ON: u16 = 0x0316;
/// `resume label` 
pub const RESUME_LABEL: u16 = 0x031E;
/// `resume` 
pub const RESUME: u16 = 0x0330;
/// `pop proc` 
pub const POP_PROC: u16 = 0x033C;
/// `every` I
pub const EVERY: u16 = 0x034A;
/// `step` 
pub const STEP: u16 = 0x0356;
/// `return` I
pub const RETURN: u16 = 0x0360;
/// `pop` I
pub const POP: u16 = 0x036C;
/// `procedure` 
pub const PROCEDURE: u16 = 0x0376;
/// `proc` 
pub const PROC: u16 = 0x0386;
/// `end proc` 
pub const END_PROC: u16 = 0x0390;
/// `shared` 
pub const SHARED: u16 = 0x039E;
/// `global` 
pub const GLOBAL: u16 = 0x03AA;
/// `end` I
pub const END: u16 = 0x03B6;
/// `stop` I
pub const STOP: u16 = 0x03C0;
/// `param#` 0
pub const PARAM_F: u16 = 0x03CA;
/// `param$` 2
pub const PARAM_S: u16 = 0x03D6;
/// `param` 0
pub const PARAM: u16 = 0x03E2;
/// `error` I0
pub const ERROR: u16 = 0x03EE;
/// `errn` 0
pub const ERRN: u16 = 0x03FA;
/// `data` 
pub const DATA: u16 = 0x0404;
/// `read` 
pub const READ: u16 = 0x040E;
/// `restore` 
pub const RESTORE: u16 = 0x0418;
/// `break off` I
pub const BREAK_OFF: u16 = 0x0426;
/// `break on` I
pub const BREAK_ON: u16 = 0x0436;
/// `inc` I
pub const INC: u16 = 0x0444;
/// `dec` I
pub const DEC: u16 = 0x044E;
/// `add` I
pub const ADD: u16 = 0x0458;
/// `add` I
pub const ADD_2: u16 = 0x0462;
/// `print #` 
pub const PRINT_HASH: u16 = 0x046A;
/// `print` I
pub const PRINT: u16 = 0x0476;
/// `lprint` I
pub const LPRINT: u16 = 0x0482;
/// `input$` 20
pub const INPUT_S: u16 = 0x048E;
/// `input$` 20,0
pub const INPUT_S_2: u16 = 0x049C;
/// `using` I
pub const USING: u16 = 0x04A6;
/// `input #` 
pub const INPUT_HASH: u16 = 0x04B2;
/// `line input #` 
pub const LINE_INPUT_HASH: u16 = 0x04BE;
/// `input` I
pub const INPUT: u16 = 0x04D0;
/// `line input` I
pub const LINE_INPUT: u16 = 0x04DC;
/// `run` I
pub const RUN: u16 = 0x04EC;
/// `run` I2
pub const RUN_2: u16 = 0x04F6;
/// `set buffer` I
pub const SET_BUFFER: u16 = 0x04FE;
/// `mid$` 22,0,0
pub const MID_S: u16 = 0x050E;
/// `mid$` 22,0
pub const MID_S_2: u16 = 0x051E;
/// `left$` 22,0
pub const LEFT_S: u16 = 0x0528;
/// `right$` 22,0
pub const RIGHT_S: u16 = 0x0536;
/// `flip$` 22
pub const FLIP_S: u16 = 0x0546;
/// `chr$` 20
pub const CHR_S: u16 = 0x0552;
/// `space$` 20
pub const SPACE_S: u16 = 0x055E;
/// `string$` 22,0
pub const STRING_S: u16 = 0x056C;
/// `upper$` 22
pub const UPPER_S: u16 = 0x057C;
/// `lower$` 22
pub const LOWER_S: u16 = 0x058A;
/// `str$` 24
pub const STR_S: u16 = 0x0598;
/// `val` 02
pub const VAL: u16 = 0x05A4;
/// `bin$` 20
pub const BIN_S: u16 = 0x05AE;
/// `bin$` 20,0
pub const BIN_S_2: u16 = 0x05BA;
/// `hex$` 20
pub const HEX_S: u16 = 0x05C4;
/// `hex$` 20,0
pub const HEX_S_2: u16 = 0x05D0;
/// `len` 02
pub const LEN: u16 = 0x05DA;
/// `instr` 02,2
pub const INSTR: u16 = 0x05E4;
/// `instr` 02,2,0
pub const INSTR_2: u16 = 0x05F4;
/// `tab$` 2
pub const TAB_S: u16 = 0x0600;
/// `free` 0
pub const FREE: u16 = 0x060A;
/// `varptr` 0
pub const VARPTR: u16 = 0x0614;
/// `remember x` I
pub const REMEMBER_X: u16 = 0x0620;
/// `remember y` I
pub const REMEMBER_Y: u16 = 0x0630;
/// `dim` I
pub const DIM: u16 = 0x0640;
/// `rem` 
pub const REM: u16 = 0x064A;
/// `'` 
pub const T_: u16 = 0x0652;
/// `sort` I
pub const SORT: u16 = 0x0658;
/// `match` 03,3
pub const MATCH: u16 = 0x0662;
/// `edit` I
pub const EDIT: u16 = 0x0670;
/// `direct` I
pub const DIRECT: u16 = 0x067A;
/// `rnd` 00
pub const RND: u16 = 0x0686;
/// `randomize` I0
pub const RANDOMIZE: u16 = 0x0690;
/// `sgn` 04
pub const SGN: u16 = 0x06A0;
/// `abs` 44
pub const ABS: u16 = 0x06AA;
/// `int` 44
pub const INT: u16 = 0x06B4;
/// `radian` I
pub const RADIAN: u16 = 0x06BE;
/// `degree` I
pub const DEGREE: u16 = 0x06CA;
/// `pi#` 1
pub const PI_F: u16 = 0x06D6;
/// `fix` I0
pub const FIX: u16 = 0x06E0;
/// `min` 00,0
pub const MIN: u16 = 0x06EA;
/// `max` 00,0
pub const MAX: u16 = 0x06F6;
/// `sin` 15
pub const SIN: u16 = 0x0702;
/// `cos` 15
pub const COS: u16 = 0x070C;
/// `tan` 15
pub const TAN: u16 = 0x0716;
/// `asin` 11
pub const ASIN: u16 = 0x0720;
/// `acos` 11
pub const ACOS: u16 = 0x072C;
/// `atan` 11
pub const ATAN: u16 = 0x0738;
/// `hsin` 15
pub const HSIN: u16 = 0x0744;
/// `hcos` 15
pub const HCOS: u16 = 0x0750;
/// `htan` 15
pub const HTAN: u16 = 0x075C;
/// `sqr` 11
pub const SQR: u16 = 0x0768;
/// `log` 11
pub const LOG: u16 = 0x0772;
/// `ln` 11
pub const LN: u16 = 0x077C;
/// `exp` 11
pub const EXP: u16 = 0x0786;
/// `menu to bank` I0
pub const MENU_TO_BANK: u16 = 0x0790;
/// `bank to menu` I0
pub const BANK_TO_MENU: u16 = 0x07A4;
/// `menu on` I
pub const MENU_ON: u16 = 0x07B8;
/// `menu off` I
pub const MENU_OFF: u16 = 0x07C6;
/// `menu calc` I
pub const MENU_CALC: u16 = 0x07D4;
/// `menu mouse on` I
pub const MENU_MOUSE_ON: u16 = 0x07E4;
/// `menu mouse off` I
pub const MENU_MOUSE_OFF: u16 = 0x07F8;
/// `menu base` I0,0
pub const MENU_BASE: u16 = 0x080C;
/// `set menu` I0t0,0
pub const SET_MENU: u16 = 0x081E;
/// `x menu` 00
pub const X_MENU: u16 = 0x0832;
/// `y menu` 00
pub const Y_MENU: u16 = 0x0840;
/// `menu key` I0t0,0
pub const MENU_KEY: u16 = 0x084E;
/// `menu bar` I0
pub const MENU_BAR: u16 = 0x0862;
/// `menu line` I0
pub const MENU_LINE: u16 = 0x0872;
/// `menu tline` I0
pub const MENU_TLINE: u16 = 0x0882;
/// `menu movable` I0
pub const MENU_MOVABLE: u16 = 0x0894;
/// `menu static` I0
pub const MENU_STATIC: u16 = 0x08A8;
/// `menu item movable` I0
pub const MENU_ITEM_MOVABLE: u16 = 0x08BA;
/// `menu item static` I0
pub const MENU_ITEM_STATIC: u16 = 0x08D2;
/// `menu active` I0
pub const MENU_ACTIVE: u16 = 0x08EA;
/// `menu inactive` I0
pub const MENU_INACTIVE: u16 = 0x08FC;
/// `menu separate` I0
pub const MENU_SEPARATE: u16 = 0x0910;
/// `menu link` I0
pub const MENU_LINK: u16 = 0x0924;
/// `menu called` I0
pub const MENU_CALLED: u16 = 0x0934;
/// `menu once` I0
pub const MENU_ONCE: u16 = 0x0946;
/// `menu del` I
pub const MENU_DEL: u16 = 0x0956;
/// `menu$` V
pub const MENU_S: u16 = 0x0964;
/// `choice` 0
pub const CHOICE: u16 = 0x0970;
/// `choice` 00
pub const CHOICE_2: u16 = 0x097E;
/// `screen copy` I0t0
pub const SCREEN_COPY: u16 = 0x0986;
/// `screen copy` I0t00
pub const SCREEN_COPY_2: u16 = 0x099C;
/// `screen copy` I0,0,0,0,0t0,0,0
pub const SCREEN_COPY_3: u16 = 0x09A8;
/// `screen copy` I0,0,0,0,0t0,0,0,0
pub const SCREEN_COPY_4: u16 = 0x09BE;
/// `screen clone` I0
pub const SCREEN_CLONE: u16 = 0x09D6;
/// `screen open` I0,0,0,0,0
pub const SCREEN_OPEN: u16 = 0x09EA;
/// `screen close` I0
pub const SCREEN_CLOSE: u16 = 0x0A04;
/// `screen display` I0,0,0,0,0
pub const SCREEN_DISPLAY: u16 = 0x0A18;
/// `screen offset` I0,0,0
pub const SCREEN_OFFSET: u16 = 0x0A36;
/// `screen size` 
pub const SCREEN_SIZE: u16 = 0x0A4E;
/// `screen colour` 0
pub const SCREEN_COLOUR: u16 = 0x0A5E;
/// `screen to front` I
pub const SCREEN_TO_FRONT: u16 = 0x0A72;
/// `screen to front` I0
pub const SCREEN_TO_FRONT_2: u16 = 0x0A88;
/// `screen to back` I
pub const SCREEN_TO_BACK: u16 = 0x0A90;
/// `screen to back` I0
pub const SCREEN_TO_BACK_2: u16 = 0x0AA6;
/// `screen hide` I
pub const SCREEN_HIDE: u16 = 0x0AAE;
/// `screen hide` I0
pub const SCREEN_HIDE_2: u16 = 0x0AC0;
/// `screen show` I
pub const SCREEN_SHOW: u16 = 0x0AC8;
/// `screen show` I0
pub const SCREEN_SHOW_2: u16 = 0x0ADA;
/// `screen swap` I
pub const SCREEN_SWAP: u16 = 0x0AE2;
/// `screen swap` I0
pub const SCREEN_SWAP_2: u16 = 0x0AF4;
/// `save iff` I2
pub const SAVE_IFF: u16 = 0x0AFC;
/// `save iff` I2,0
pub const SAVE_IFF_2: u16 = 0x0B0C;
/// `view` I
pub const VIEW: u16 = 0x0B16;
/// `auto view off` I
pub const AUTO_VIEW_OFF: u16 = 0x0B20;
/// `auto view on` I
pub const AUTO_VIEW_ON: u16 = 0x0B34;
/// `screen base` 0
pub const SCREEN_BASE: u16 = 0x0B46;
/// `screen width` 0
pub const SCREEN_WIDTH: u16 = 0x0B58;
/// `screen width` 00
pub const SCREEN_WIDTH_2: u16 = 0x0B6C;
/// `screen height` 0
pub const SCREEN_HEIGHT: u16 = 0x0B74;
/// `screen height` 00
pub const SCREEN_HEIGHT_2: u16 = 0x0B88;
/// `get palette` I0
pub const GET_PALETTE: u16 = 0x0B90;
/// `get palette` I0,0
pub const GET_PALETTE_2: u16 = 0x0BA4;
/// `cls` I
pub const CLS: u16 = 0x0BAE;
/// `cls` I0
pub const CLS_2: u16 = 0x0BB8;
/// `cls` I0,0,0t0,0
pub const CLS_3: u16 = 0x0BC0;
/// `def scroll` I0,0,0t0,0,0,0
pub const DEF_SCROLL: u16 = 0x0BD0;
/// `x hard` 00
pub const X_HARD: u16 = 0x0BEE;
/// `x hard` 00,0
pub const X_HARD_2: u16 = 0x0BFC;
/// `y hard` 00
pub const Y_HARD: u16 = 0x0C06;
/// `y hard` 00,0
pub const Y_HARD_2: u16 = 0x0C14;
/// `x screen` 00
pub const X_SCREEN: u16 = 0x0C1E;
/// `x screen` 00,0
pub const X_SCREEN_2: u16 = 0x0C2E;
/// `y screen` 00
pub const Y_SCREEN: u16 = 0x0C38;
/// `y screen` 00,0
pub const Y_SCREEN_2: u16 = 0x0C48;
/// `x text` 00
pub const X_TEXT: u16 = 0x0C52;
/// `y text` 00
pub const Y_TEXT: u16 = 0x0C60;
/// `screen` I0
pub const SCREEN: u16 = 0x0C6E;
/// `screen` 0
pub const SCREEN_2: u16 = 0x0C7C;
/// `hires` 0
pub const HIRES: u16 = 0x0C84;
/// `lowres` 0
pub const LOWRES: u16 = 0x0C90;
/// `dual playfield` I0,0
pub const DUAL_PLAYFIELD: u16 = 0x0C9C;
/// `dual priority` I0,0
pub const DUAL_PRIORITY: u16 = 0x0CB4;
/// `wait vbl` I
pub const WAIT_VBL: u16 = 0x0CCA;
/// `default palette` I
pub const DEFAULT_PALETTE: u16 = 0x0CD8;
/// `default` I
pub const DEFAULT: u16 = 0x0CEE;
/// `palette` I
pub const PALETTE: u16 = 0x0CFC;
/// `colour back` I0
pub const COLOUR_BACK: u16 = 0x0D0A;
/// `colour` I0,0
pub const COLOUR: u16 = 0x0D1C;
/// `colour` 00
pub const COLOUR_2: u16 = 0x0D2C;
/// `flash off` I
pub const FLASH_OFF: u16 = 0x0D34;
/// `flash` I0,2
pub const FLASH: u16 = 0x0D44;
/// `shift off` I
pub const SHIFT_OFF: u16 = 0x0D52;
/// `shift up` I0,0,0,0
pub const SHIFT_UP: u16 = 0x0D62;
/// `shift down` I0,0,0,0
pub const SHIFT_DOWN: u16 = 0x0D78;
/// `set rainbow` I0,0,0,2,2,2
pub const SET_RAINBOW: u16 = 0x0D90;
/// `set rainbow` I0,0,0,2,2,2,0
pub const SET_RAINBOW_2: u16 = 0x0DAE;
/// `rainbow del` I
pub const RAINBOW_DEL: u16 = 0x0DC2;
/// `rainbow del` I0
pub const RAINBOW_DEL_2: u16 = 0x0DD4;
/// `rainbow` I0,0,0,0
pub const RAINBOW: u16 = 0x0DDC;
/// `rain` V00,0
pub const RAIN: u16 = 0x0DF0;
/// `fade` I
pub const FADE: u16 = 0x0DFE;
/// `phybase` 00
pub const PHYBASE: u16 = 0x0E08;
/// `physic` 0
pub const PHYSIC: u16 = 0x0E16;
/// `physic` 00
pub const PHYSIC_2: u16 = 0x0E24;
/// `autoback` I0
pub const AUTOBACK: u16 = 0x0E2C;
/// `plot` I0,0
pub const PLOT: u16 = 0x0E3C;
/// `plot` I0,0,0
pub const PLOT_2: u16 = 0x0E4A;
/// `point` 00,0
pub const POINT: u16 = 0x0E56;
/// `draw to` I0,0
pub const DRAW_TO: u16 = 0x0E64;
/// `draw` I0,0t0,0
pub const DRAW: u16 = 0x0E74;
/// `ellipse` I0,0,0,0
pub const ELLIPSE: u16 = 0x0E86;
/// `circle` I0,0,0
pub const CIRCLE: u16 = 0x0E9A;
/// `polyline` I
pub const POLYLINE: u16 = 0x0EAC;
/// `polygon` I
pub const POLYGON: u16 = 0x0EBA;
/// `bar` I0,0t0,0
pub const BAR: u16 = 0x0EC8;
/// `box` I0,0t0,0
pub const BOX: u16 = 0x0ED8;
/// `paint` I0,0
pub const PAINT: u16 = 0x0EE8;
/// `paint` I0,0,0
pub const PAINT_2: u16 = 0x0EF8;
/// `gr locate` I0,0
pub const GR_LOCATE: u16 = 0x0F04;
/// `text length` 02
pub const TEXT_LENGTH: u16 = 0x0F16;
/// `text styles` 0
pub const TEXT_STYLES: u16 = 0x0F28;
/// `text base` 0
pub const TEXT_BASE: u16 = 0x0F3A;
/// `text` I0,0,2
pub const TEXT: u16 = 0x0F4A;
/// `set text` I0
pub const SET_TEXT: u16 = 0x0F5A;
/// `set paint` I0
pub const SET_PAINT: u16 = 0x0F6A;
/// `get fonts` I
pub const GET_FONTS: u16 = 0x0F7A;
/// `get disc fonts` I
pub const GET_DISC_FONTS: u16 = 0x0F8A;
/// `get rom fonts` I
pub const GET_ROM_FONTS: u16 = 0x0F9E;
/// `set font` I0
pub const SET_FONT: u16 = 0x0FB2;
/// `font$` 20
pub const FONT_S: u16 = 0x0FC2;
/// `hslider` I0,0t0,0,0,0,0
pub const HSLIDER: u16 = 0x0FCE;
/// `vslider` I0,0t0,0,0,0,0
pub const VSLIDER: u16 = 0x0FE8;
/// `set slider` I0,0,0,0,0,0,0,0
pub const SET_SLIDER: u16 = 0x1002;
/// `set pattern` I0
pub const SET_PATTERN: u16 = 0x1022;
/// `set line` I0
pub const SET_LINE: u16 = 0x1034;
/// `ink` I0
pub const INK: u16 = 0x1044;
/// `ink` I0,0
pub const INK_2: u16 = 0x1050;
/// `ink` I0,0,0
pub const INK_3: u16 = 0x105A;
/// `gr writing` I0
pub const GR_WRITING: u16 = 0x1066;
/// `clip` I
pub const CLIP: u16 = 0x1078;
/// `clip` I0,0t0,0
pub const CLIP_2: u16 = 0x1084;
/// `set tempras` I
pub const SET_TEMPRAS: u16 = 0x1092;
/// `set tempras` I0
pub const SET_TEMPRAS_2: u16 = 0x10A4;
/// `set tempras` I0,0
pub const SET_TEMPRAS_3: u16 = 0x10AC;
/// `appear` I0t0,0
pub const APPEAR: u16 = 0x10B6;
/// `appear` I0t0,0,0
pub const APPEAR_2: u16 = 0x10C8;
/// `zoom` I0,0,0,0,0t0,0,0,0,0
pub const ZOOM: u16 = 0x10D6;
/// `get cblock` I0,0,0,0,0
pub const GET_CBLOCK: u16 = 0x10F4;
/// `put cblock` I0
pub const PUT_CBLOCK: u16 = 0x110E;
/// `put cblock` I0,0,0
pub const PUT_CBLOCK_2: u16 = 0x1120;
/// `del cblock` I
pub const DEL_CBLOCK: u16 = 0x112C;
/// `del cblock` I0
pub const DEL_CBLOCK_2: u16 = 0x113E;
/// `get block` I0,0,0,0,0
pub const GET_BLOCK: u16 = 0x1146;
/// `get block` I0,0,0,0,0,0
pub const GET_BLOCK_2: u16 = 0x1160;
/// `put block` I0
pub const PUT_BLOCK: u16 = 0x1172;
/// `put block` I0,0,0
pub const PUT_BLOCK_2: u16 = 0x1184;
/// `put block` I0,0,0,0
pub const PUT_BLOCK_3: u16 = 0x1190;
/// `put block` I0,0,0,0,0
pub const PUT_BLOCK_4: u16 = 0x119E;
/// `del block` I
pub const DEL_BLOCK: u16 = 0x11AE;
/// `del block` I0
pub const DEL_BLOCK_2: u16 = 0x11BE;
/// `key speed` I0,0
pub const KEY_SPEED: u16 = 0x11C6;
/// `key state` 00
pub const KEY_STATE: u16 = 0x11D8;
/// `key shift` 0
pub const KEY_SHIFT: u16 = 0x11E8;
/// `joy` 00
pub const JOY: u16 = 0x11F8;
/// `jup` 00
pub const JUP: u16 = 0x1202;
/// `jdown` 00
pub const JDOWN: u16 = 0x120C;
/// `jleft` 00
pub const JLEFT: u16 = 0x1218;
/// `jright` 00
pub const JRIGHT: u16 = 0x1224;
/// `fire` 00
pub const FIRE: u16 = 0x1232;
/// `true` 0
pub const TRUE: u16 = 0x123E;
/// `false` 0
pub const FALSE: u16 = 0x1248;
/// `put key` I2
pub const PUT_KEY: u16 = 0x1254;
/// `scancode` 0
pub const SCANCODE: u16 = 0x1262;
/// `scanshift` 0
pub const SCANSHIFT: u16 = 0x1270;
/// `clear key` I
pub const CLEAR_KEY: u16 = 0x1280;
/// `wait key` I
pub const WAIT_KEY: u16 = 0x1290;
/// `wait` I0
pub const WAIT: u16 = 0x129E;
/// `key$` V20
pub const KEY_S: u16 = 0x12AA;
/// `scan$` 20
pub const SCAN_S: u16 = 0x12B6;
/// `scan$` 20,0
pub const SCAN_S_2: u16 = 0x12C4;
/// `timer` V0
pub const TIMER: u16 = 0x12CE;
/// `wind open` I0,0,0,0,0
pub const WIND_OPEN: u16 = 0x12DA;
/// `wind open` I0,0,0,0,0,0
pub const WIND_OPEN_2: u16 = 0x12F4;
/// `wind open` I0,0,0,0,0,0,0
pub const WIND_OPEN_3: u16 = 0x1306;
/// `wind close` I
pub const WIND_CLOSE: u16 = 0x131A;
/// `wind save` I
pub const WIND_SAVE: u16 = 0x132A;
/// `wind move` I0,0
pub const WIND_MOVE: u16 = 0x133A;
/// `wind size` I0,0
pub const WIND_SIZE: u16 = 0x134C;
/// `window` I0
pub const WINDOW: u16 = 0x135E;
/// `windon` 0
pub const WINDON: u16 = 0x136C;
/// `locate` I0,0
pub const LOCATE: u16 = 0x1378;
/// `clw` I
pub const CLW: u16 = 0x1388;
/// `home` I
pub const HOME: u16 = 0x1392;
/// `curs pen` I0
pub const CURS_PEN: u16 = 0x139C;
/// `pen$` 20
pub const PEN_S: u16 = 0x13AC;
/// `paper$` 20
pub const PAPER_S: u16 = 0x13B8;
/// `at` 20,0
pub const AT: u16 = 0x13C6;
/// `pen` I0
pub const PEN: u16 = 0x13D2;
/// `paper` I0
pub const PAPER: u16 = 0x13DC;
/// `centre` I2
pub const CENTRE: u16 = 0x13E8;
/// `border` I0,0,0
pub const BORDER: u16 = 0x13F6;
/// `writing` I0
pub const WRITING: u16 = 0x1408;
/// `writing` I0,0
pub const WRITING_2: u16 = 0x1418;
/// `title top` I2
pub const TITLE_TOP: u16 = 0x1422;
/// `title bottom` I2
pub const TITLE_BOTTOM: u16 = 0x1432;
/// `curs off` I
pub const CURS_OFF: u16 = 0x1446;
/// `curs on` I
pub const CURS_ON: u16 = 0x1454;
/// `inverse off` I
pub const INVERSE_OFF: u16 = 0x1462;
/// `inverse on` I
pub const INVERSE_ON: u16 = 0x1474;
/// `under off` I
pub const UNDER_OFF: u16 = 0x1484;
/// `under on` I
pub const UNDER_ON: u16 = 0x1494;
/// `shade off` I
pub const SHADE_OFF: u16 = 0x14A2;
/// `shade on` I
pub const SHADE_ON: u16 = 0x14B2;
/// `scroll off` I
pub const SCROLL_OFF: u16 = 0x14C0;
/// `scroll on` I
pub const SCROLL_ON: u16 = 0x14D0;
/// `scroll` I0
pub const SCROLL: u16 = 0x14E0;
/// `cup$` 2
pub const CUP_S: u16 = 0x14EE;
/// `cdown$` 2
pub const CDOWN_S: u16 = 0x14F8;
/// `cleft$` 2
pub const CLEFT_S: u16 = 0x1504;
/// `cright$` 2
pub const CRIGHT_S: u16 = 0x1510;
/// `cup` I
pub const CUP: u16 = 0x151E;
/// `cdown` I
pub const CDOWN: u16 = 0x1528;
/// `cleft` I
pub const CLEFT: u16 = 0x1534;
/// `cright` I
pub const CRIGHT: u16 = 0x1540;
/// `memorize x` I
pub const MEMORIZE_X: u16 = 0x154C;
/// `memorize y` I
pub const MEMORIZE_Y: u16 = 0x155C;
/// `cmove$` 20,0
pub const CMOVE_S: u16 = 0x156C;
/// `cmove` I0,0
pub const CMOVE: u16 = 0x157C;
/// `cline` I
pub const CLINE: u16 = 0x158A;
/// `cline` I0
pub const CLINE_2: u16 = 0x1596;
/// `hscroll` I0
pub const HSCROLL: u16 = 0x159E;
/// `vscroll` I0
pub const VSCROLL: u16 = 0x15AC;
/// `set tab` I0
pub const SET_TAB: u16 = 0x15BA;
/// `set curs` I0,0,0,0,0,0,0,0
pub const SET_CURS: u16 = 0x15C8;
/// `x curs` 0
pub const X_CURS: u16 = 0x15E6;
/// `y curs` 0
pub const Y_CURS: u16 = 0x15F2;
/// `x graphic` 00
pub const X_GRAPHIC: u16 = 0x15FE;
/// `y graphic` 00
pub const Y_GRAPHIC: u16 = 0x160E;
/// `xgr` 0
pub const XGR: u16 = 0x161E;
/// `ygr` 0
pub const YGR: u16 = 0x1628;
/// `reserve zone` I
pub const RESERVE_ZONE: u16 = 0x1632;
/// `reserve zone` I0
pub const RESERVE_ZONE_2: u16 = 0x1646;
/// `reset zone` I
pub const RESET_ZONE: u16 = 0x164E;
/// `reset zone` I0
pub const RESET_ZONE_2: u16 = 0x1660;
/// `set zone` I0,0,0t0,0
pub const SET_ZONE: u16 = 0x1668;
/// `zone` 00,0
pub const ZONE: u16 = 0x1680;
/// `zone` 00,0,0
pub const ZONE_2: u16 = 0x168E;
/// `hzone` 00,0
pub const HZONE: u16 = 0x169A;
/// `hzone` 00,0,0
pub const HZONE_2: u16 = 0x16AA;
/// `scin` 00,0
pub const SCIN: u16 = 0x16B6;
/// `scin` 00,0,0
pub const SCIN_2: u16 = 0x16C4;
/// `mouse screen` 0
pub const MOUSE_SCREEN: u16 = 0x16D0;
/// `mouse zone` 0
pub const MOUSE_ZONE: u16 = 0x16E2;
/// `set input` I0,0
pub const SET_INPUT: u16 = 0x16F2;
/// `close workbench` I
pub const CLOSE_WORKBENCH: u16 = 0x1704;
/// `close editor` I
pub const CLOSE_EDITOR: u16 = 0x171A;
/// `dir first$` 22
pub const DIR_FIRST_S: u16 = 0x172C;
/// `dir next$` 2
pub const DIR_NEXT_S: u16 = 0x173E;
/// `exist` 02
pub const EXIST: u16 = 0x174E;
/// `dir$` V2
pub const DIR_S: u16 = 0x175A;
/// `ldir/w` I
pub const LDIR_W: u16 = 0x1766;
/// `ldir/w` I2
pub const LDIR_W_2: u16 = 0x1774;
/// `dir/w` I
pub const DIR_W: u16 = 0x177C;
/// `dir/w` I2
pub const DIR_W_2: u16 = 0x1788;
/// `ldir` I
pub const LDIR: u16 = 0x1790;
/// `ldir` I2
pub const LDIR_2: u16 = 0x179C;
/// `dir` I
pub const DIR: u16 = 0x17A4;
/// `dir` I2
pub const DIR_2: u16 = 0x17AE;
/// `set dir` I0
pub const SET_DIR: u16 = 0x17B6;
/// `set dir` I0,2
pub const SET_DIR_2: u16 = 0x17C4;
/// `load iff` I2
pub const LOAD_IFF: u16 = 0x17D4;
/// `load iff` I2,0
pub const LOAD_IFF_2: u16 = 0x17E4;
/// `mask iff` I0
pub const MASK_IFF: u16 = 0x17EE;
/// `picture` 0
pub const PICTURE: u16 = 0x17FE;
/// `bload` I2,0
pub const BLOAD: u16 = 0x180C;
/// `bsave` I2,0t0
pub const BSAVE: u16 = 0x181A;
/// `pload` I2,0
pub const PLOAD: u16 = 0x182A;
/// `save` I2
pub const SAVE: u16 = 0x1838;
/// `save` I2,0
pub const SAVE_2: u16 = 0x1844;
/// `load` I2
pub const LOAD: u16 = 0x184E;
/// `load` I2,0
pub const LOAD_2: u16 = 0x185A;
/// `dfree` 0
pub const DFREE: u16 = 0x1864;
/// `mkdir` I2
pub const MKDIR: u16 = 0x1870;
/// `lof` 00
pub const LOF: u16 = 0x187C;
/// `eof` 00
pub const EOF: u16 = 0x1886;
/// `pof` V00
pub const POF: u16 = 0x1890;
/// `port` 00
pub const PORT: u16 = 0x189C;
/// `open random` I0,2
pub const OPEN_RANDOM: u16 = 0x18A8;
/// `open in` I0,2
pub const OPEN_IN: u16 = 0x18BC;
/// `open out` I0,2
pub const OPEN_OUT: u16 = 0x18CC;
/// `open port` I0,2
pub const OPEN_PORT: u16 = 0x18DE;
/// `append` I0,2
pub const APPEND: u16 = 0x18F0;
/// `close` I
pub const CLOSE: u16 = 0x1900;
/// `close` I0
pub const CLOSE_2: u16 = 0x190C;
/// `parent` I
pub const PARENT: u16 = 0x1914;
/// `rename` I2t2
pub const RENAME: u16 = 0x1920;
/// `kill` I2
pub const KILL: u16 = 0x1930;
/// `drive` 02
pub const DRIVE: u16 = 0x193C;
/// `field` I
pub const FIELD: u16 = 0x1948;
/// `fsel$` 22
pub const FSEL_S: u16 = 0x1954;
/// `fsel$` 22,2
pub const FSEL_S_2: u16 = 0x1962;
/// `fsel$` 22,2,2
pub const FSEL_S_3: u16 = 0x196C;
/// `fsel$` 22,2,2,2
pub const FSEL_S_4: u16 = 0x1978;
/// `set sprite buffer` I0
pub const SET_SPRITE_BUFFER: u16 = 0x1986;
/// `sprite off` I
pub const SPRITE_OFF: u16 = 0x199E;
/// `sprite off` I0
pub const SPRITE_OFF_2: u16 = 0x19B0;
/// `sprite priority` I0
pub const SPRITE_PRIORITY: u16 = 0x19B8;
/// `sprite update off` I
pub const SPRITE_UPDATE_OFF: u16 = 0x19CE;
/// `sprite update on` I
pub const SPRITE_UPDATE_ON: u16 = 0x19E6;
/// `sprite update` I
pub const SPRITE_UPDATE: u16 = 0x19FC;
/// `spritebob col` 00
pub const SPRITEBOB_COL: u16 = 0x1A10;
/// `spritebob col` 00,0t0
pub const SPRITEBOB_COL_2: u16 = 0x1A26;
/// `sprite col` 00
pub const SPRITE_COL: u16 = 0x1A32;
/// `sprite col` 00,0t0
pub const SPRITE_COL_2: u16 = 0x1A44;
/// `set hardcol` I0,0
pub const SET_HARDCOL: u16 = 0x1A50;
/// `hardcol` 00
pub const HARDCOL: u16 = 0x1A64;
/// `sprite base` 00
pub const SPRITE_BASE: u16 = 0x1A72;
/// `icon base` 00
pub const ICON_BASE: u16 = 0x1A84;
/// `sprite` I0,0,0,0
pub const SPRITE: u16 = 0x1A94;
/// `bob off` I
pub const BOB_OFF: u16 = 0x1AA8;
/// `bob off` I0
pub const BOB_OFF_2: u16 = 0x1AB6;
/// `bob update off` I
pub const BOB_UPDATE_OFF: u16 = 0x1ABE;
/// `bob update on` I
pub const BOB_UPDATE_ON: u16 = 0x1AD2;
/// `bob update` I
pub const BOB_UPDATE: u16 = 0x1AE6;
/// `bob clear` I
pub const BOB_CLEAR: u16 = 0x1AF6;
/// `bob draw` I
pub const BOB_DRAW: u16 = 0x1B06;
/// `bobsprite col` 00
pub const BOBSPRITE_COL: u16 = 0x1B14;
/// `bobsprite col` 00,0t0
pub const BOBSPRITE_COL_2: u16 = 0x1B2A;
/// `bob col` 00
pub const BOB_COL: u16 = 0x1B36;
/// `bob col` 00,0t0
pub const BOB_COL_2: u16 = 0x1B46;
/// `col` 00
pub const COL: u16 = 0x1B52;
/// `limit bob` I
pub const LIMIT_BOB: u16 = 0x1B5C;
/// `limit bob` I0,0t0,0
pub const LIMIT_BOB_2: u16 = 0x1B6C;
/// `limit bob` I0,0,0t0,0
pub const LIMIT_BOB_3: u16 = 0x1B7A;
/// `set bob` I0,0,0,0
pub const SET_BOB: u16 = 0x1B8A;
/// `bob` I0,0,0,0
pub const BOB: u16 = 0x1B9E;
/// `get sprite palette` I
pub const GET_SPRITE_PALETTE: u16 = 0x1BAE;
/// `get sprite palette` I0
pub const GET_SPRITE_PALETTE_2: u16 = 0x1BC8;
/// `get sprite` I0,0,0t0,0
pub const GET_SPRITE: u16 = 0x1BD0;
/// `get sprite` I0,0,0,0t0,0
pub const GET_SPRITE_2: u16 = 0x1BEA;
/// `get bob` I0,0,0t0,0
pub const GET_BOB: u16 = 0x1BFC;
/// `get bob` I0,0,0,0t0,0
pub const GET_BOB_2: u16 = 0x1C14;
/// `del sprite` I0
pub const DEL_SPRITE: u16 = 0x1C26;
/// `del sprite` I0t0
pub const DEL_SPRITE_2: u16 = 0x1C38;
/// `del bob` I0
pub const DEL_BOB: u16 = 0x1C42;
/// `del bob` I0t0
pub const DEL_BOB_2: u16 = 0x1C52;
/// `del icon` I0
pub const DEL_ICON: u16 = 0x1C5C;
/// `del icon` I0t0
pub const DEL_ICON_2: u16 = 0x1C6C;
/// `ins sprite` I0
pub const INS_SPRITE: u16 = 0x1C76;
/// `ins bob` I0
pub const INS_BOB: u16 = 0x1C88;
/// `ins icon` I0
pub const INS_ICON: u16 = 0x1C96;
/// `get icon palette` I
pub const GET_ICON_PALETTE: u16 = 0x1CA6;
/// `get icon palette` I0
pub const GET_ICON_PALETTE_2: u16 = 0x1CBE;
/// `get icon` I0,0,0t0,0
pub const GET_ICON: u16 = 0x1CC6;
/// `get icon` I0,0,0,0t0,0
pub const GET_ICON_2: u16 = 0x1CDE;
/// `put bob` I0
pub const PUT_BOB: u16 = 0x1CF0;
/// `paste bob` I0,0,0
pub const PASTE_BOB: u16 = 0x1CFE;
/// `paste icon` I0,0,0
pub const PASTE_ICON: u16 = 0x1D12;
/// `make mask` I
pub const MAKE_MASK: u16 = 0x1D28;
/// `make mask` I0
pub const MAKE_MASK_2: u16 = 0x1D38;
/// `no mask` I
pub const NO_MASK: u16 = 0x1D40;
/// `no mask` I0
pub const NO_MASK_2: u16 = 0x1D4E;
/// `make icon mask` I
pub const MAKE_ICON_MASK: u16 = 0x1D56;
/// `make icon mask` I0
pub const MAKE_ICON_MASK_2: u16 = 0x1D6C;
/// `no icon mask` I
pub const NO_ICON_MASK: u16 = 0x1D74;
/// `no icon mask` I0
pub const NO_ICON_MASK_2: u16 = 0x1D88;
/// `hot spot` I0,0
pub const HOT_SPOT: u16 = 0x1D90;
/// `hot spot` I0,0,0
pub const HOT_SPOT_2: u16 = 0x1DA2;
/// `priority on` I
pub const PRIORITY_ON: u16 = 0x1DAE;
/// `priority off` I
pub const PRIORITY_OFF: u16 = 0x1DC0;
/// `hide on` I
pub const HIDE_ON: u16 = 0x1DD2;
/// `hide` I
pub const HIDE: u16 = 0x1DE0;
/// `show on` I
pub const SHOW_ON: u16 = 0x1DEA;
/// `show` I
pub const SHOW: u16 = 0x1DF8;
/// `change mouse` I0
pub const CHANGE_MOUSE: u16 = 0x1E02;
/// `x mouse` V0
pub const X_MOUSE: u16 = 0x1E16;
/// `y mouse` V0
pub const Y_MOUSE: u16 = 0x1E24;
/// `mouse key` 0
pub const MOUSE_KEY: u16 = 0x1E32;
/// `mouse click` 0
pub const MOUSE_CLICK: u16 = 0x1E42;
/// `limit mouse` I
pub const LIMIT_MOUSE: u16 = 0x1E54;
/// `limit mouse` I0
pub const LIMIT_MOUSE_2: u16 = 0x1E66;
/// `limit mouse` I0,0t0,0
pub const LIMIT_MOUSE_3: u16 = 0x1E6E;
/// `unfreeze` I
pub const UNFREEZE: u16 = 0x1E7C;
/// `move x` I0,3
pub const MOVE_X: u16 = 0x1E8A;
/// `move x` I0,2t0
pub const MOVE_X_2: u16 = 0x1E9A;
/// `move y` I0,3
pub const MOVE_Y: u16 = 0x1EA6;
/// `move y` I0,2t0
pub const MOVE_Y_2: u16 = 0x1EB6;
/// `move off` I
pub const MOVE_OFF: u16 = 0x1EC2;
/// `move off` I0
pub const MOVE_OFF_2: u16 = 0x1ED2;
/// `move on` I
pub const MOVE_ON: u16 = 0x1EDA;
/// `move on` I0
pub const MOVE_ON_2: u16 = 0x1EE8;
/// `move freeze` I
pub const MOVE_FREEZE: u16 = 0x1EF0;
/// `move freeze` I0
pub const MOVE_FREEZE_2: u16 = 0x1F02;
/// `anim off` I
pub const ANIM_OFF: u16 = 0x1F0A;
/// `anim off` I0
pub const ANIM_OFF_2: u16 = 0x1F1A;
/// `anim on` I
pub const ANIM_ON: u16 = 0x1F22;
/// `anim on` I0
pub const ANIM_ON_2: u16 = 0x1F30;
/// `anim freeze` I
pub const ANIM_FREEZE: u16 = 0x1F38;
/// `anim freeze` I0
pub const ANIM_FREEZE_2: u16 = 0x1F4A;
/// `anim` I0,3
pub const ANIM: u16 = 0x1F52;
/// `anim freeze` I0,2t0
pub const ANIM_FREEZE_3: u16 = 0x1F60;
/// `movon` 00
pub const MOVON: u16 = 0x1F6C;
/// `chanan` 00
pub const CHANAN: u16 = 0x1F78;
/// `chanmv` 00
pub const CHANMV: u16 = 0x1F86;
/// `channel` I
pub const CHANNEL: u16 = 0x1F94;
/// `amreg` V00
pub const AMREG: u16 = 0x1FA2;
/// `amreg` V00,0
pub const AMREG_2: u16 = 0x1FB0;
/// `amal on` I
pub const AMAL_ON: u16 = 0x1FBC;
/// `amal on` I0
pub const AMAL_ON_2: u16 = 0x1FCA;
/// `amal off` I
pub const AMAL_OFF: u16 = 0x1FD2;
/// `amal off` I0
pub const AMAL_OFF_2: u16 = 0x1FE2;
/// `amal freeze` I
pub const AMAL_FREEZE: u16 = 0x1FEA;
/// `amal freeze` I0
pub const AMAL_FREEZE_2: u16 = 0x1FFC;
/// `amalerr` 0
pub const AMALERR: u16 = 0x2004;
/// `amal` I0,3
pub const AMAL: u16 = 0x2012;
/// `amal` I0,2t0
pub const AMAL_2: u16 = 0x2020;
/// `amplay` I0,0
pub const AMPLAY: u16 = 0x202C;
/// `amplay` I0,0,0t0
pub const AMPLAY_2: u16 = 0x203C;
/// `synchro on` I
pub const SYNCHRO_ON: u16 = 0x204A;
/// `synchro off` I
pub const SYNCHRO_OFF: u16 = 0x205A;
/// `synchro` I
pub const SYNCHRO: u16 = 0x206C;
/// `update off` I
pub const UPDATE_OFF: u16 = 0x207A;
/// `update on` I
pub const UPDATE_ON: u16 = 0x208A;
/// `update every` I0
pub const UPDATE_EVERY: u16 = 0x209A;
/// `update` I
pub const UPDATE: u16 = 0x20AE;
/// `x bob` 00
pub const X_BOB: u16 = 0x20BA;
/// `y bob` 00
pub const Y_BOB: u16 = 0x20C6;
/// `x sprite` 00
pub const X_SPRITE: u16 = 0x20D2;
/// `y sprite` 00
pub const Y_SPRITE: u16 = 0x20E2;
/// `reserve as work` I0,0
pub const RESERVE_AS_WORK: u16 = 0x20F2;
/// `reserve as chip work` I0,0
pub const RESERVE_AS_CHIP_WORK: u16 = 0x210A;
/// `reserve as data` I0,0
pub const RESERVE_AS_DATA: u16 = 0x2128;
/// `reserve as chip data` I0,0
pub const RESERVE_AS_CHIP_DATA: u16 = 0x2140;
/// `erase` I0
pub const ERASE: u16 = 0x215E;
/// `list bank` I
pub const LIST_BANK: u16 = 0x216A;
/// `chip free` 0
pub const CHIP_FREE: u16 = 0x217A;
/// `fast free` 0
pub const FAST_FREE: u16 = 0x218A;
/// `fill` I0t0,0
pub const FILL: u16 = 0x219A;
/// `copy` I0,0t0
pub const COPY: u16 = 0x21AA;
/// `hunt` 00t0,2
pub const HUNT: u16 = 0x21BA;
/// `poke` I0,0
pub const POKE: u16 = 0x21CA;
/// `loke` I0,0
pub const LOKE: u16 = 0x21D8;
/// `peek` 00
pub const PEEK: u16 = 0x21E6;
/// `deek` 00
pub const DEEK: u16 = 0x21F2;
/// `leek` 00
pub const LEEK: u16 = 0x21FE;
/// `bset` I0,0
pub const BSET: u16 = 0x220A;
/// `bclr` I0,0
pub const BCLR: u16 = 0x2218;
/// `bchg` I0,0
pub const BCHG: u16 = 0x2226;
/// `btst` 00,0
pub const BTST: u16 = 0x2234;
/// `ror.b` I0,0
pub const ROR_B: u16 = 0x2242;
/// `ror.w` I0,0
pub const ROR_W: u16 = 0x2250;
/// `ror.l` I0,0
pub const ROR_L: u16 = 0x225E;
/// `rol.b` I0,0
pub const ROL_B: u16 = 0x226C;
/// `rol.w` I0,0
pub const ROL_W: u16 = 0x227A;
/// `rol.l` I0,0
pub const ROL_L: u16 = 0x2288;
/// `areg` V00
pub const AREG: u16 = 0x2296;
/// `dreg` V00
pub const DREG: u16 = 0x22A2;
/// `copper on` I
pub const COPPER_ON: u16 = 0x22AE;
/// `copper off` I
pub const COPPER_OFF: u16 = 0x22BE;
/// `cop swap` I
pub const COP_SWAP: u16 = 0x22CE;
/// `cop reset` I
pub const COP_RESET: u16 = 0x22DC;
/// `cop wait` I0,0
pub const COP_WAIT: u16 = 0x22EC;
/// `cop wait` I0,0,0,0
pub const COP_WAIT_2: u16 = 0x22FE;
/// `cop movel` I0,0
pub const COP_MOVEL: u16 = 0x230C;
/// `cop move` I0,0
pub const COP_MOVE: u16 = 0x231E;
/// `cop logic` 0
pub const COP_LOGIC: u16 = 0x2330;
/// `prg first$` 22
pub const PRG_FIRST_S: u16 = 0x2340;
/// `prg next$` 2
pub const PRG_NEXT_S: u16 = 0x2352;
/// `psel$` 22
pub const PSEL_S: u16 = 0x2362;
/// `psel$` 22,2
pub const PSEL_S_2: u16 = 0x2370;
/// `psel$` 22,2,2
pub const PSEL_S_3: u16 = 0x237A;
/// `psel$` 22,2,2,2
pub const PSEL_S_4: u16 = 0x2386;
/// `prun` I2
pub const PRUN: u16 = 0x2394;
/// `bgrab` I0
pub const BGRAB: u16 = 0x23A0;
/// `put` I0,0
pub const PUT: u16 = 0x23AC;
/// `get` I0,0
pub const GET: u16 = 0x23B8;
/// `system` I
pub const SYSTEM: u16 = 0x23C4;
/// `multi wait` I
pub const MULTI_WAIT: u16 = 0x23D0;
/// `i bob` 00
pub const I_BOB: u16 = 0x23E0;
/// `i sprite` 00
pub const I_SPRITE: u16 = 0x23EC;
/// `priority reverse on` I
pub const PRIORITY_REVERSE_ON: u16 = 0x23FC;
/// `priority reverse off` I
pub const PRIORITY_REVERSE_OFF: u16 = 0x2416;
/// `dev first$` 22
pub const DEV_FIRST_S: u16 = 0x2430;
/// `dev next$` 2
pub const DEV_NEXT_S: u16 = 0x2442;
/// `hrev block` I0
pub const HREV_BLOCK: u16 = 0x2452;
/// `vrev block` I0
pub const VREV_BLOCK: u16 = 0x2464;
/// `hrev` 00
pub const HREV: u16 = 0x2476;
/// `vrev` 00
pub const VREV: u16 = 0x2482;
/// `rev` 00
pub const REV: u16 = 0x248E;
/// `bank swap` I0,0
pub const BANK_SWAP: u16 = 0x2498;
/// `amos to front` I
pub const AMOS_TO_FRONT: u16 = 0x24AA;
/// `amos to back` I
pub const AMOS_TO_BACK: u16 = 0x24BE;
/// `amos here` 0
pub const AMOS_HERE: u16 = 0x24D0;
/// `amos lock` I
pub const AMOS_LOCK: u16 = 0x24E0;
/// `amos unlock` I
pub const AMOS_UNLOCK: u16 = 0x24F0;
/// `display height` 0
pub const DISPLAY_HEIGHT: u16 = 0x2502;
/// `ntsc` 0
pub const NTSC: u16 = 0x2516;
/// `laced` 0
pub const LACED: u16 = 0x2520;
/// `prg state` 0
pub const PRG_STATE: u16 = 0x252C;
/// `command line$` V2
pub const COMMAND_LINE_S: u16 = 0x253C;
/// `disc info$` 22
pub const DISC_INFO_S: u16 = 0x2550;
/// `\\\\\\\\\\\\\\\/` I
pub const T__2: u16 = 0x2562;
/// `set accessory` I
pub const SET_ACCESSORY: u16 = 0x2578;
/// `trap` I
pub const TRAP: u16 = 0x259A;
/// `else if` 
pub const ELSE_IF: u16 = 0x25A4;
/// `include` I2
pub const INCLUDE: u16 = 0x25B2;
/// `array` 03
pub const ARRAY: u16 = 0x25C0;
/// `frame load` 00t0
pub const FRAME_LOAD: u16 = 0x25CC;
/// `frame load` 00t0,0
pub const FRAME_LOAD_2: u16 = 0x25E0;
/// `frame play` 00,0
pub const FRAME_PLAY: u16 = 0x25EC;
/// `frame play` 00,0,0
pub const FRAME_PLAY_2: u16 = 0x2600;
/// `iff anim` I2t0
pub const IFF_ANIM: u16 = 0x260C;
/// `iff anim` I2t0,0
pub const IFF_ANIM_2: u16 = 0x261E;
/// `frame length` 00
pub const FRAME_LENGTH: u16 = 0x262A;
/// `frame length` 00,0
pub const FRAME_LENGTH_2: u16 = 0x263E;
/// `frame skip` 00
pub const FRAME_SKIP: u16 = 0x2648;
/// `frame skip` 00,0
pub const FRAME_SKIP_2: u16 = 0x265A;
/// `frame param` 0
pub const FRAME_PARAM: u16 = 0x2664;
/// `call editor` I0
pub const CALL_EDITOR: u16 = 0x2676;
/// `call editor` I0,0
pub const CALL_EDITOR_2: u16 = 0x268A;
/// `call editor` I0,0,2
pub const CALL_EDITOR_3: u16 = 0x2694;
/// `ask editor` I0
pub const ASK_EDITOR: u16 = 0x26A0;
/// `ask editor` I0,0
pub const ASK_EDITOR_2: u16 = 0x26B2;
/// `ask editor` I0,0,2
pub const ASK_EDITOR_3: u16 = 0x26BC;
/// `erase temp` I
pub const ERASE_TEMP: u16 = 0x26C8;
/// `erase all` I
pub const ERASE_ALL: u16 = 0x26D8;
/// `dialog box` 03
pub const DIALOG_BOX: u16 = 0x26E8;
/// `dialog box` 03,0
pub const DIALOG_BOX_2: u16 = 0x26FA;
/// `dialog box` 03,0,2
pub const DIALOG_BOX_3: u16 = 0x2704;
/// `dialog box` 03,0,2,0,0
pub const DIALOG_BOX_4: u16 = 0x2710;
/// `dialog open` I0,3
pub const DIALOG_OPEN: u16 = 0x2720;
/// `dialog open` I0,3,0
pub const DIALOG_OPEN_2: u16 = 0x2736;
/// `dialog open` I0,3,0,0
pub const DIALOG_OPEN_3: u16 = 0x2742;
/// `dialog close` I
pub const DIALOG_CLOSE: u16 = 0x2750;
/// `dialog close` I0
pub const DIALOG_CLOSE_2: u16 = 0x2764;
/// `dialog run` 00
pub const DIALOG_RUN: u16 = 0x276C;
/// `dialog run` 00,0
pub const DIALOG_RUN_2: u16 = 0x277E;
/// `dialog run` 00,0,0,0
pub const DIALOG_RUN_3: u16 = 0x2788;
/// `dialog` 00
pub const DIALOG: u16 = 0x2796;
/// `vdialog` V00,0
pub const VDIALOG: u16 = 0x27A4;
/// `vdialog$` V20,0
pub const VDIALOG_S: u16 = 0x27B6;
/// `rdialog` 00,0
pub const RDIALOG: u16 = 0x27C8;
/// `rdialog` 00,0,0
pub const RDIALOG_2: u16 = 0x27DA;
/// `rdialog$` 20,0
pub const RDIALOG_S: u16 = 0x27E6;
/// `rdialog$` 20,0,0
pub const RDIALOG_S_2: u16 = 0x27F8;
/// `edialog` 0
pub const EDIALOG: u16 = 0x2804;
/// `dialog clr` I0
pub const DIALOG_CLR: u16 = 0x2812;
/// `dialog update` I0,0
pub const DIALOG_UPDATE: u16 = 0x2824;
/// `dialog update` I0,0,3
pub const DIALOG_UPDATE_2: u16 = 0x283C;
/// `dialog update` I0,0,3,0
pub const DIALOG_UPDATE_3: u16 = 0x2848;
/// `dialog update` I0,0,3,0,0
pub const DIALOG_UPDATE_4: u16 = 0x2856;
/// `dialog freeze` I
pub const DIALOG_FREEZE: u16 = 0x2866;
/// `dialog freeze` I0
pub const DIALOG_FREEZE_2: u16 = 0x287A;
/// `dialog unfreeze` I
pub const DIALOG_UNFREEZE: u16 = 0x2882;
/// `dialog unfreeze` I0
pub const DIALOG_UNFREEZE_2: u16 = 0x2898;
/// `poke$` I0,2
pub const POKE_S: u16 = 0x28A0;
/// `peek$` 20,0
pub const PEEK_S: u16 = 0x28AE;
/// `peek$` 20,0,2
pub const PEEK_S_2: u16 = 0x28BE;
/// `resource bank` I0
pub const RESOURCE_BANK: u16 = 0x28CA;
/// `resource$` 20
pub const RESOURCE_S: u16 = 0x28DE;
/// `resource screen open` I0,0,0,0
pub const RESOURCE_SCREEN_OPEN: u16 = 0x28EE;
/// `resource unpack` I0,0,0
pub const RESOURCE_UNPACK: u16 = 0x2910;
/// `read text` I2
pub const READ_TEXT: u16 = 0x292A;
/// `` I2,0,0
pub const T__3: u16 = 0x293A;
/// `err$` 20
pub const ERR_S: u16 = 0x2946;
/// `assign` I2t2
pub const ASSIGN: u16 = 0x2952;
/// `errtrap` 0
pub const ERRTRAP: u16 = 0x2962;
/// `dev open` I0,2,0,0,0
pub const DEV_OPEN: u16 = 0x2970;
/// `dev close` I
pub const DEV_CLOSE: u16 = 0x2988;
/// `dev close` I0
pub const DEV_CLOSE_2: u16 = 0x2998;
/// `dev base` 00
pub const DEV_BASE: u16 = 0x29A0;
/// `dev do` I0,0
pub const DEV_DO: u16 = 0x29B0;
/// `dev send` I0,0
pub const DEV_SEND: u16 = 0x29C0;
/// `dev abort` I0
pub const DEV_ABORT: u16 = 0x29D2;
/// `dev check` 00
pub const DEV_CHECK: u16 = 0x29E2;
/// `lib open` I0,2,0
pub const LIB_OPEN: u16 = 0x29F2;
/// `lib close` I
pub const LIB_CLOSE: u16 = 0x2A06;
/// `lib close` I0
pub const LIB_CLOSE_2: u16 = 0x2A16;
/// `lib call` 00,0
pub const LIB_CALL: u16 = 0x2A1E;
/// `lib base` 00
pub const LIB_BASE: u16 = 0x2A30;
/// `equ` 02
pub const EQU: u16 = 0x2A40;
/// `lvo` 02
pub const LVO: u16 = 0x2A4A;
/// `struc` V00,2
pub const STRUC: u16 = 0x2A54;
/// `struc$` V20,2
pub const STRUC_S: u16 = 0x2A64;
/// `bstart` 00
pub const BSTART: u16 = 0x2A74;
/// `blength` 00
pub const BLENGTH: u16 = 0x2A82;
/// `bsend` I0
pub const BSEND: u16 = 0x2A90;
/// `bank shrink` I0t0
pub const BANK_SHRINK: u16 = 0x2A9C;
/// `prg under` 0
pub const PRG_UNDER: u16 = 0x2AB0;
/// `arexx open` I2
pub const AREXX_OPEN: u16 = 0x2AC0;
/// `arexx close` I
pub const AREXX_CLOSE: u16 = 0x2AD2;
/// `arexx exist` 02
pub const AREXX_EXIST: u16 = 0x2AE4;
/// `arexx` 0
pub const AREXX: u16 = 0x2AF6;
/// `arexx$` 20
pub const AREXX_S: u16 = 0x2B02;
/// `arexx wait` I
pub const AREXX_WAIT: u16 = 0x2B10;
/// `arexx answer` I0
pub const AREXX_ANSWER: u16 = 0x2B20;
/// `arexx answer` I0,2
pub const AREXX_ANSWER_2: u16 = 0x2B34;
/// `exec` I2
pub const EXEC: u16 = 0x2B3E;
/// `monitor` I
pub const MONITOR: u16 = 0x2B4A;
/// `screen mode` 0
pub const SCREEN_MODE: u16 = 0x2B58;
/// `arexx answer` C3
pub const AREXX_ANSWER_3: u16 = 0x2B6A;
/// `kill editor` I
pub const KILL_EDITOR: u16 = 0x2B72;
/// `set double precision` I
pub const SET_DOUBLE_PRECISION: u16 = 0x2B84;
/// `set stack` I
pub const SET_STACK: u16 = 0x2B9E;
/// `get bob palette` I
pub const GET_BOB_PALETTE: u16 = 0x2BAE;
/// `get bob palette` I0
pub const GET_BOB_PALETTE_2: u16 = 0x2BC4;
/// `set equate bank` I0
pub const SET_EQUATE_BANK: u16 = 0x2BCC;
/// `zdialog` 00,0,0
pub const ZDIALOG: u16 = 0x2BE2;
/// `||apcmp||` I
pub const APCMP: u16 = 0x2BF4;
pub const OP_XOR: u16 = 0xFF3E;
pub const OP_OR: u16 = 0xFF4C;
pub const OP_AND: u16 = 0xFF58;
pub const OP_NE: u16 = 0xFF66;
pub const OP_NE2: u16 = 0xFF70;
pub const OP_LE: u16 = 0xFF7A;
pub const OP_LE2: u16 = 0xFF84;
pub const OP_GE: u16 = 0xFF8E;
pub const OP_GE2: u16 = 0xFF98;
pub const OP_EQ: u16 = 0xFFA2;
pub const OP_LT: u16 = 0xFFAC;
pub const OP_GT: u16 = 0xFFB6;
pub const OP_PLUS: u16 = 0xFFC0;
pub const OP_MINUS: u16 = 0xFFCA;
pub const OP_MOD: u16 = 0xFFD4;
pub const OP_MUL: u16 = 0xFFE2;
pub const OP_DIV: u16 = 0xFFEC;
pub const OP_POW: u16 = 0xFFF6;
/// `mubase` 0
pub const MUSIC_MUBASE: u16 = 0x0006;
/// `vumeter` 00
pub const MUSIC_VUMETER: u16 = 0x0012;
/// `voice` I0
pub const MUSIC_VOICE: u16 = 0x0020;
/// `music off` I
pub const MUSIC_MUSIC_OFF: u16 = 0x002C;
/// `music stop` I
pub const MUSIC_MUSIC_STOP: u16 = 0x003C;
/// `tempo` I0
pub const MUSIC_TEMPO: u16 = 0x004C;
/// `music` I0
pub const MUSIC_MUSIC: u16 = 0x0058;
/// `noise to` I0
pub const MUSIC_NOISE_TO: u16 = 0x0064;
/// `boom` I
pub const MUSIC_BOOM: u16 = 0x0074;
/// `shoot` I
pub const MUSIC_SHOOT: u16 = 0x007E;
/// `sam bank` I0
pub const MUSIC_SAM_BANK: u16 = 0x008A;
/// `sam loop on` I
pub const MUSIC_SAM_LOOP_ON: u16 = 0x009A;
/// `sam loop on` I
pub const MUSIC_SAM_LOOP_ON_2: u16 = 0x00AC;
/// `sam loop off` I
pub const MUSIC_SAM_LOOP_OFF: u16 = 0x00B4;
/// `sam loop on` I0
pub const MUSIC_SAM_LOOP_ON_3: u16 = 0x00C6;
/// `sample` I0t0
pub const MUSIC_SAMPLE: u16 = 0x00CE;
/// `sam play` I0
pub const MUSIC_SAM_PLAY: u16 = 0x00DE;
/// `sam play` I0,0
pub const MUSIC_SAM_PLAY_2: u16 = 0x00EE;
/// `sam play` I0,0,0
pub const MUSIC_SAM_PLAY_3: u16 = 0x00F8;
/// `sam raw` I0,0,0,0
pub const MUSIC_SAM_RAW: u16 = 0x0104;
/// `bell` I
pub const MUSIC_BELL: u16 = 0x0118;
/// `bell` I0
pub const MUSIC_BELL_2: u16 = 0x0124;
/// `play off` I
pub const MUSIC_PLAY_OFF: u16 = 0x012C;
/// `play off` I0
pub const MUSIC_PLAY_OFF_2: u16 = 0x013C;
/// `play` I0,0
pub const MUSIC_PLAY: u16 = 0x0144;
/// `play` I0,0,0
pub const MUSIC_PLAY_2: u16 = 0x0152;
/// `set wave` I0,2
pub const MUSIC_SET_WAVE: u16 = 0x015E;
/// `del wave` I0
pub const MUSIC_DEL_WAVE: u16 = 0x0170;
/// `set envel` I0,0t0,0
pub const MUSIC_SET_ENVEL: u16 = 0x0180;
/// `mvolume` I0
pub const MUSIC_MVOLUME: u16 = 0x0196;
/// `volume` I0
pub const MUSIC_VOLUME: u16 = 0x01A4;
/// `volume` I0,0
pub const MUSIC_VOLUME_2: u16 = 0x01B2;
/// `wave` I0t0
pub const MUSIC_WAVE: u16 = 0x01BC;
/// `led on` I
pub const MUSIC_LED_ON: u16 = 0x01CA;
/// `led off` I
pub const MUSIC_LED_OFF: u16 = 0x01D6;
/// `say` I2
pub const MUSIC_SAY: u16 = 0x01E4;
/// `say` I2,0
pub const MUSIC_SAY_2: u16 = 0x01F0;
/// `set talk` I0,0,0,0
pub const MUSIC_SET_TALK: u16 = 0x01FA;
/// `sload` I0t0,0
pub const MUSIC_SLOAD: u16 = 0x0210;
/// `sam swapped` 00
pub const MUSIC_SAM_SWAPPED: u16 = 0x0220;
/// `sam swap` I0t0,0
pub const MUSIC_SAM_SWAP: u16 = 0x0232;
/// `sam stop` I
pub const MUSIC_SAM_STOP: u16 = 0x0246;
/// `sam stop` I0
pub const MUSIC_SAM_STOP_2: u16 = 0x0256;
/// `track stop` I
pub const MUSIC_TRACK_STOP: u16 = 0x025E;
/// `track loop on` I
pub const MUSIC_TRACK_LOOP_ON: u16 = 0x026E;
/// `track loop of` I
pub const MUSIC_TRACK_LOOP_OF: u16 = 0x0282;
/// `track play` I
pub const MUSIC_TRACK_PLAY: u16 = 0x0296;
/// `track play` I0
pub const MUSIC_TRACK_PLAY_2: u16 = 0x02A8;
/// `track play` I0,0
pub const MUSIC_TRACK_PLAY_3: u16 = 0x02B0;
/// `track load` I2,0
pub const MUSIC_TRACK_LOAD: u16 = 0x02BA;
/// `mouth width` 0
pub const MUSIC_MOUTH_WIDTH: u16 = 0x02CE;
/// `mouth height` 0
pub const MUSIC_MOUTH_HEIGHT: u16 = 0x02E0;
/// `mouth read` I
pub const MUSIC_MOUTH_READ: u16 = 0x02F2;
/// `talk stop` I
pub const MUSIC_TALK_STOP: u16 = 0x0302;
/// `talk misc` I0,0
pub const MUSIC_TALK_MISC: u16 = 0x0312;
/// `ssave` I0,0t0
pub const MUSIC_SSAVE: u16 = 0x0324;
/// `med load` I2,0
pub const MUSIC_MED_LOAD: u16 = 0x0334;
/// `med play` I
pub const MUSIC_MED_PLAY: u16 = 0x0346;
/// `med play` I0
pub const MUSIC_MED_PLAY_2: u16 = 0x0356;
/// `med play` I0,0
pub const MUSIC_MED_PLAY_3: u16 = 0x035E;
/// `med stop` I
pub const MUSIC_MED_STOP: u16 = 0x0368;
/// `med cont` I
pub const MUSIC_MED_CONT: u16 = 0x0376;
/// `med midi on` I
pub const MUSIC_MED_MIDI_ON: u16 = 0x0384;
/// `pack` I0t0
pub const COMPACT_PACK: u16 = 0x0006;
/// `pack` I0t0,0,0,0,0
pub const COMPACT_PACK_2: u16 = 0x0014;
/// `spack` I0t0
pub const COMPACT_SPACK: u16 = 0x0026;
/// `spack` I0t0,0,0,0,0
pub const COMPACT_SPACK_2: u16 = 0x0036;
/// `unpack` I0
pub const COMPACT_UNPACK: u16 = 0x0048;
/// `unpack` I0t0
pub const COMPACT_UNPACK_2: u16 = 0x0056;
/// `unpack` I0,0,0
pub const COMPACT_UNPACK_3: u16 = 0x0060;
/// `request on` I
pub const REQUEST_REQUEST_ON: u16 = 0x0006;
/// `request off` I
pub const REQUEST_REQUEST_OFF: u16 = 0x0016;
/// `request wb` I
pub const REQUEST_REQUEST_WB: u16 = 0x0028;
/// `td debug` I0
pub const TD_TD_DEBUG: u16 = 0x0006;
/// `td load` I2
pub const TD_TD_LOAD: u16 = 0x0016;
/// `td clear all` I
pub const TD_TD_CLEAR_ALL: u16 = 0x0024;
/// `td object` I0,2,0,0,0,0,0,0
pub const TD_TD_OBJECT: u16 = 0x0036;
/// `td screen height` I0
pub const TD_TD_SCREEN_HEIGHT: u16 = 0x0054;
/// `td visible` 00
pub const TD_TD_VISIBLE: u16 = 0x006C;
/// `td range` 00,0
pub const TD_TD_RANGE: u16 = 0x007E;
/// `td kill` I0
pub const TD_TD_KILL: u16 = 0x0090;
/// `td move x` I0,2
pub const TD_TD_MOVE_X: u16 = 0x009E;
/// `td move y` I0,2
pub const TD_TD_MOVE_Y: u16 = 0x00B0;
/// `td move z` I0,2
pub const TD_TD_MOVE_Z: u16 = 0x00C2;
/// `td move rel` I0,0,0,0
pub const TD_TD_MOVE_REL: u16 = 0x00D4;
/// `td move` I0,0,0,0
pub const TD_TD_MOVE: u16 = 0x00EC;
/// `td forward` I0,0
pub const TD_TD_FORWARD: u16 = 0x0100;
/// `td position x` 00
pub const TD_TD_POSITION_X: u16 = 0x0114;
/// `td position y` 00
pub const TD_TD_POSITION_Y: u16 = 0x0128;
/// `td position z` 00
pub const TD_TD_POSITION_Z: u16 = 0x013C;
/// `td angle a` I0,2
pub const TD_TD_ANGLE_A: u16 = 0x0150;
/// `td angle b` I0,2
pub const TD_TD_ANGLE_B: u16 = 0x0164;
/// `td angle c` I0,2
pub const TD_TD_ANGLE_C: u16 = 0x0178;
/// `td angle rel` I0,0,0,0
pub const TD_TD_ANGLE_REL: u16 = 0x018C;
/// `td angle` I0,0,0,0
pub const TD_TD_ANGLE: u16 = 0x01A6;
/// `td attitude a` 00
pub const TD_TD_ATTITUDE_A: u16 = 0x01BC;
/// `td attitude b` 00
pub const TD_TD_ATTITUDE_B: u16 = 0x01D0;
/// `td attitude c` 00
pub const TD_TD_ATTITUDE_C: u16 = 0x01E4;
/// `td face` I0,0
pub const TD_TD_FACE: u16 = 0x01F8;
/// `td face` I0,0,0,0
pub const TD_TD_FACE_2: u16 = 0x020A;
/// `td bearing a` 0
pub const TD_TD_BEARING_A: u16 = 0x0218;
/// `td bearing a` 00,0
pub const TD_TD_BEARING_A_2: u16 = 0x022C;
/// `td bearing a` 00,0,0,0
pub const TD_TD_BEARING_A_3: u16 = 0x0236;
/// `td bearing b` 0
pub const TD_TD_BEARING_B: u16 = 0x0244;
/// `td bearing b` 00,0
pub const TD_TD_BEARING_B_2: u16 = 0x0258;
/// `td bearing b` 00,0,0,0
pub const TD_TD_BEARING_B_3: u16 = 0x0262;
/// `td bearing r` 0
pub const TD_TD_BEARING_R: u16 = 0x0270;
/// `td bearing r` 00,0
pub const TD_TD_BEARING_R_2: u16 = 0x0284;
/// `td bearing r` 00,0,0,0
pub const TD_TD_BEARING_R_3: u16 = 0x028E;
/// `td anim rel` I0,0,0,0,0,0
pub const TD_TD_ANIM_REL: u16 = 0x029C;
/// `td anim point x` 00,0
pub const TD_TD_ANIM_POINT_X: u16 = 0x02B8;
/// `td anim point y` 00,0
pub const TD_TD_ANIM_POINT_Y: u16 = 0x02D0;
/// `td anim point z` 00,0
pub const TD_TD_ANIM_POINT_Z: u16 = 0x02E8;
/// `td anim` I0,0,0,0,0,0
pub const TD_TD_ANIM: u16 = 0x0300;
/// `td redraw` I
pub const TD_TD_REDRAW: u16 = 0x0318;
/// `td set zone` I0,0,0,0,0,0
pub const TD_TD_SET_ZONE: u16 = 0x0328;
/// `td collide` 00
pub const TD_TD_COLLIDE: u16 = 0x0344;
/// `td collide` 00,0
pub const TD_TD_COLLIDE_2: u16 = 0x0356;
/// `td zone x` 00,0
pub const TD_TD_ZONE_X: u16 = 0x0360;
/// `td zone y` 00,0
pub const TD_TD_ZONE_Y: u16 = 0x0372;
/// `td zone z` 00,0
pub const TD_TD_ZONE_Z: u16 = 0x0384;
/// `td zone r` 00,0
pub const TD_TD_ZONE_R: u16 = 0x0396;
/// `td world x` 0
pub const TD_TD_WORLD_X: u16 = 0x03A8;
/// `td world x` 00,0,0,0
pub const TD_TD_WORLD_X_2: u16 = 0x03BA;
/// `td world y` 0
pub const TD_TD_WORLD_Y: u16 = 0x03C8;
/// `td world y` 00,0,0,0
pub const TD_TD_WORLD_Y_2: u16 = 0x03DA;
/// `td world z` 0
pub const TD_TD_WORLD_Z: u16 = 0x03E8;
/// `td world z` 00,0,0,0
pub const TD_TD_WORLD_Z_2: u16 = 0x03FA;
/// `td view x` 0
pub const TD_TD_VIEW_X: u16 = 0x0408;
/// `td view x` 00,0,0,0
pub const TD_TD_VIEW_X_2: u16 = 0x0418;
/// `td view y` 0
pub const TD_TD_VIEW_Y: u16 = 0x0426;
/// `td view y` 00,0,0,0
pub const TD_TD_VIEW_Y_2: u16 = 0x0436;
/// `td view z` 0
pub const TD_TD_VIEW_Z: u16 = 0x0444;
/// `td view z` 00,0,0,0
pub const TD_TD_VIEW_Z_2: u16 = 0x0454;
/// `td screen x` 0
pub const TD_TD_SCREEN_X: u16 = 0x0462;
/// `td screen x` 00,0,0
pub const TD_TD_SCREEN_X_2: u16 = 0x0474;
/// `td screen y` 0
pub const TD_TD_SCREEN_Y: u16 = 0x0480;
/// `td screen y` 00,0,0
pub const TD_TD_SCREEN_Y_2: u16 = 0x0492;
/// `td background` I0,0,0,0,0t0,0
pub const TD_TD_BACKGROUND: u16 = 0x049E;
/// `td background` I0,0,0,0,0t0,0,0
pub const TD_TD_BACKGROUND_2: u16 = 0x04C0;
/// `td dir` I2
pub const TD_TD_DIR: u16 = 0x04D6;
/// `td surface points off` I
pub const TD_TD_SURFACE_POINTS_OFF: u16 = 0x04E4;
/// `td surface points` I0,0,0,0
pub const TD_TD_SURFACE_POINTS: u16 = 0x0500;
/// `td surface` I2,0,0t0,0,0,0
pub const TD_TD_SURFACE: u16 = 0x051E;
/// `td cls` I
pub const TD_TD_CLS: u16 = 0x053C;
/// `td keep on` I
pub const TD_TD_KEEP_ON: u16 = 0x0548;
/// `td keep off` I
pub const TD_TD_KEEP_OFF: u16 = 0x0558;
/// `td advanced` 00
pub const TD_TD_ADVANCED: u16 = 0x056A;
/// `td quit` I
pub const TD_TD_QUIT: u16 = 0x057C;
/// `td priority` I0,0
pub const TD_TD_PRIORITY: u16 = 0x058A;
/// `td pragma status` 00,0
pub const TD_TD_PRAGMA_STATUS: u16 = 0x059E;
/// `td pragma` I0,0
pub const TD_TD_PRAGMA: u16 = 0x05B8;
/// `td delete zone` I0,0
pub const TD_TD_DELETE_ZONE: u16 = 0x05CA;
/// `td set colour` I0,0,0
pub const TD_TD_SET_COLOUR: u16 = 0x05E2;
/// `td rotate` I0,0,0,0
pub const TD_TD_ROTATE: u16 = 0x05FA;
/// `cmpcall` I
pub const COMP_CMPCALL: u16 = 0x0006;
/// `comp options` I2
pub const COMP_COMP_OPTIONS: u16 = 0x0014;
/// `comp test on` I
pub const COMP_COMP_TEST_ON: u16 = 0x0028;
/// `comp test off` I
pub const COMP_COMP_TEST_OFF: u16 = 0x003A;
/// `comp test` I
pub const COMP_COMP_TEST: u16 = 0x004E;
/// `compile` I2
pub const COMP_COMPILE: u16 = 0x005E;
/// `compile` I2,0
pub const COMP_COMPILE_2: u16 = 0x006E;
/// `comp err$` 2
pub const COMP_COMP_ERR_S: u16 = 0x0078;
/// `comp load` I
pub const COMP_COMP_LOAD: u16 = 0x0088;
/// `comp load` I2
pub const COMP_COMP_LOAD_2: u16 = 0x0098;
/// `comp del` I
pub const COMP_COMP_DEL: u16 = 0x00A0;
/// `comp here` 0
pub const COMP_COMP_HERE: u16 = 0x00AE;
/// `comp size` 0
pub const COMP_COMP_SIZE: u16 = 0x00BE;
/// `squash` 00,0,0,0,0
pub const COMP_SQUASH: u16 = 0x00CE;
/// `unsquash` 00,0
pub const COMP_UNSQUASH: u16 = 0x00E4;
/// `ppsave` I2,0
pub const COMP_PPSAVE: u16 = 0x00F6;
/// `ppsave` I2,0,0
pub const COMP_PPSAVE_2: u16 = 0x0106;
/// `ppload` I2
pub const COMP_PPLOAD: u16 = 0x0112;
/// `ppload` I2,0
pub const COMP_PPLOAD_2: u16 = 0x0120;
/// `serial open` I0,0
pub const IO_SERIAL_OPEN: u16 = 0x0006;
/// `serial open` I0,0,0,0,0
pub const IO_SERIAL_OPEN_2: u16 = 0x001C;
/// `serial close` I
pub const IO_SERIAL_CLOSE: u16 = 0x002C;
/// `serial close` I0
pub const IO_SERIAL_CLOSE_2: u16 = 0x0040;
/// `serial speed` I0,0
pub const IO_SERIAL_SPEED: u16 = 0x0048;
/// `serial check` 00
pub const IO_SERIAL_CHECK: u16 = 0x005E;
/// `serial send` I0,2
pub const IO_SERIAL_SEND: u16 = 0x0072;
/// `serial speed` I0,0
pub const IO_SERIAL_SPEED_2: u16 = 0x0086;
/// `serial bits` I0,0,0
pub const IO_SERIAL_BITS: u16 = 0x009C;
/// `serial x` I0,0
pub const IO_SERIAL_X: u16 = 0x00B2;
/// `serial buf` I0,0
pub const IO_SERIAL_BUF: u16 = 0x00C4;
/// `serial parity` I0,0
pub const IO_SERIAL_PARITY: u16 = 0x00D8;
/// `serial get` 00
pub const IO_SERIAL_GET: u16 = 0x00EE;
/// `serial input$` 20
pub const IO_SERIAL_INPUT_S: u16 = 0x0100;
/// `serial fast` I0
pub const IO_SERIAL_FAST: u16 = 0x0114;
/// `serial slow` I0
pub const IO_SERIAL_SLOW: u16 = 0x0126;
/// `serial error` 00
pub const IO_SERIAL_ERROR: u16 = 0x0138;
/// `serial out` I0,0,0
pub const IO_SERIAL_OUT: u16 = 0x014C;
/// `serial status` 00
pub const IO_SERIAL_STATUS: u16 = 0x0162;
/// `serial base` 00
pub const IO_SERIAL_BASE: u16 = 0x0176;
/// `serial abort` I0
pub const IO_SERIAL_ABORT: u16 = 0x0188;
/// `printer open` I
pub const IO_PRINTER_OPEN: u16 = 0x019C;
/// `printer close` I
pub const IO_PRINTER_CLOSE: u16 = 0x01AE;
/// `printer send` I2
pub const IO_PRINTER_SEND: u16 = 0x01C2;
/// `printer out` I0,0
pub const IO_PRINTER_OUT: u16 = 0x01D6;
/// `printer dump` I
pub const IO_PRINTER_DUMP: u16 = 0x01EA;
/// `printer dump` I0,0t0,0
pub const IO_PRINTER_DUMP_2: u16 = 0x01FE;
/// `printer dump` I0,0t0,0,0,0,0
pub const IO_PRINTER_DUMP_3: u16 = 0x020C;
/// `printer abort` I
pub const IO_PRINTER_ABORT: u16 = 0x0220;
/// `printer check` 0
pub const IO_PRINTER_CHECK: u16 = 0x0234;
/// `printer online` 0
pub const IO_PRINTER_ONLINE: u16 = 0x0248;
/// `printer base` 0
pub const IO_PRINTER_BASE: u16 = 0x025C;
/// `printer error` 0
pub const IO_PRINTER_ERROR: u16 = 0x026E;
/// `parallel open` I
pub const IO_PARALLEL_OPEN: u16 = 0x0282;
/// `parallel close` I
pub const IO_PARALLEL_CLOSE: u16 = 0x0296;
/// `parallel send` I2
pub const IO_PARALLEL_SEND: u16 = 0x02AA;
/// `parallel out` I0,0
pub const IO_PARALLEL_OUT: u16 = 0x02BE;
/// `parallel abort` I
pub const IO_PARALLEL_ABORT: u16 = 0x02D4;
/// `parallel check` 0
pub const IO_PARALLEL_CHECK: u16 = 0x02E8;
/// `parallel status` 0
pub const IO_PARALLEL_STATUS: u16 = 0x02FC;
/// `parallel base` 0
pub const IO_PARALLEL_BASE: u16 = 0x0312;
/// `parallel error` 0
pub const IO_PARALLEL_ERROR: u16 = 0x0326;
/// `parallel input$` 20
pub const IO_PARALLEL_INPUT_S: u16 = 0x033A;
/// `parallel input$` 20,0
pub const IO_PARALLEL_INPUT_S_2: u16 = 0x0352;
